---

#####
base_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - coreutils
  - gnupg2
  - software-properties-common
  - syncthing
  - zsh
#####

#####
base_repositories:
  - name: "syncthing"
    repo_url: "https://apt.syncthing.net"
    gpg_url: "https://syncthing.net/release-key.gpg"
    gpg_extention: "gpg"
    components:
      - "syncthing"
      - "stable"

extra_services: []