---

base_packages:
  - coreutils
  - curl
  - docker-compose
  - git
  - jq
  - openssl
  - unzip
  - vim
  - wget
  - zsh

extra_packages:
  - docker.io
  - build-essential

laptop_extra_packages:
  - openjdk-17-jdk

packages_to_install:
  servers: "{{ base_packages + extra_packages }}"
  laptops: "{{ base_packages + extra_packages + laptop_extra_packages }}"

third_party_repositories:
  - name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
    gpgkey: https://download.docker.com/linux/fedora/gpg
  - name: 

