---

base_packages:
  - build-essential
  - coreutils
  - curl
  - docker.io
  - docker-compose
  - git
  - jq
  - openssl
  - unzip
  - vim
  - wget
  - zsh

user_home: "/home/{{ ansible_user }}"
zsh_directory: "{{ user_home }}/.zsh"

config_files:
  - file: .vimrc
    dest_path: "{{ user_home }}"
    mode: '0644'
  - file: .secrets
    dest_path: "{{ user_home }}"
    mode: '0600'
  - file: .zshrc
    dest_path: "{{ user_home }}"
    mode: '0644'
  - file: .p10k.zsh
    dest_path: "{{ zsh_directory }}"
    mode: '0644'

zsh_repositories:
  - repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_directory }}/powerlevel10k"
    depth: 1
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_directory }}/plugins/zsh-syntax-highlighting"
    depth: 0
  - repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_directory }}/plugins/zsh-autosuggestions"
    depth: 0
