---

backup_directory: "{{ documents_directory }}/Backups"

base_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - coreutils
  - curl
  - git
  - gnupg2
  - jq
  - lsb-release
  - openssl
  - software-properties-common
  - syncthing
  - unzip
  - vim
  - wget
  - zsh

base_repositories:
  - name: "docker"
    repo_url: "https://download.docker.com/linux/debian"
    gpg_url: "https://download.docker.com/linux/debian/gpg"
    gpg_extention: "asc"
    components:
      - "{{ ansible_lsb.codename }}"
      - "stable"

  - name: "syncthing"
    repo_url: "https://apt.syncthing.net"
    gpg_url: "https://syncthing.net/release-key.gpg"
    gpg_extention: "gpg"
    components:
      - "syncthing"
      - "stable"
  
config_files:
  - file: .vimrc
    dest_path: "{{ user_home }}"
    mode: '0644'
  - file: .secrets
    dest_path: "{{ user_home }}"
    mode: '0600'
  - file: .zshrc
    dest_path: "{{ user_home }}"
    mode: '0644'
  - file: .p10k.zsh
    dest_path: "{{ zsh_directory }}"
    mode: '0644'

directories:
  - "{{ documents_directory }}"
  - "{{ documents_directory }}/OS"
  - "{{ documents_directory }}/Tmp"
  - "{{ documents_directory }}/VMs"
  - "{{ documents_directory }}/Family"
  - "{{ documents_directory }}/Friends"
  - "{{ documents_directory }}/ApkApps"
  - "{{ documents_directory }}/Gallery"
  - "{{ documents_directory }}/Invoices"
  - "{{ documents_directory }}/OnlineCourses"
  - "{{ backup_directory }}"
  - "{{ backup_directory }}/Accounts"
  - "{{ backup_directory }}/Accounts/SocialMedia"
  - "{{ backup_directory }}/Accounts/Email"
  - "{{ backup_directory }}/Websites"
  - "{{ backup_directory }}/Apps"
  - "{{ backup_directory }}/Apps/Whatsapp"
  - "{{ zsh_directory }}"

docker_packages:
  - docker-ce 
  - docker-ce-cli
  - containerd.io 
  - docker-compose
  - docker-buildx-plugin 
  - docker-compose-plugin

documents_directory: "{{ user_home }}/Documents"

purge_vars:
  repositories: no
  packages: no
  shell: no
  docker: no

user_home: "/home/{{ ansible_user }}"

zsh_directory: "{{ user_home }}/.zsh"

zsh_repositories:
  - repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_directory }}/powerlevel10k"
    depth: 1
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_directory }}/plugins/zsh-syntax-highlighting"
    depth: 0
  - repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_directory }}/plugins/zsh-autosuggestions"
    depth: 0