---

- name: Template Pi-VPN config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ pivpn_config_files }}"

- name: Download Pi-VPN installer
  ansible.builtin.get_url:
    url: "{{ pivpn_installer_url }}"
    dest: /tmp/install_pivpn.sh
    mode: '0755'

- name: Run Pi-VPN installer non-interactively
  become: yes
  ansible.builtin.shell: >
    bash /tmp/install_pivpn.sh --unattended /tmp/setupVars.conf
  args:
    creates: "/etc/pivpn/wireguard/setupVars.conf"

- name: Extract WireGuard IP network portion
  block:
    - name: Get the WireGuard Address line
      command: grep Address /etc/wireguard/wg0.conf
      register: wg_address_output

    - name: Extract the first 3 octets (e.g., 10.6.0)
      set_fact:
        pivpn_network_base: "{{ wg_address_output.stdout | regex_search('Address *= *([0-9]+\\.[0-9]+\\.[0-9]+)\\.[0-9]+', '\\1') | first }}"
        # pivpn_network_base: "{{ (wg_address_output.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)\\.[0-9]+')) }}"
    
    - name: Debug the result
      debug:
        msg: "PiVPN network base is {{ pivpn_network_base }}"

- name: Add custom configs to pivpn
  ansible.builtin.lineinfile:
    path: /etc/pivpn/wireguard/setupVars.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop: 
    - regex: '^pivpnHOST'
      line: "pivpnHOST={{ pivpn_host }}"
    - regex: '^pivpnDNS1'
      line: "pivpnDNS1={{ pivpn_network_base }}.1"
    - regex: '^pivpnDNS2'
      line: "pivpnDNS2="
    - regex: '^dhcpReserv'
      line: "dhcpReserv=1"
    - regex: '^useNetworkManager'
      line: ""

- name: Reload new configs
  block:
    - name: Run pivpn debug
      ansible.builtin.shell: "Y | pivpn -d"
    - name: Restart wireguard service
      ansible.builtin.service:
        name: wg-quick@wg0
        state: restarted
        enabled: yes

- name: Add WireGuard clients
  ansible.builtin.command: "pivpn -a -n {{ item.name }} -ip {{ item.vip }}"
  args:
    creates: "/home/{{ ansible_user }}/configs/{{ item.name }}.conf"
  loop: "{{ pivpn_wireguard_clients }}"
