---

- name: Install unbound package
  ansible.builtin.package:
    name: "unbound"
    state: latest

- name: Template Unbound config file
  ansible.builtin.template:
    src: "unbound/unbound.conf.j2"
    dest: "/etc/unbound/unbound.conf.d/unbound.conf"
  notify: "Restart unbound service"

- name: Run the handler
  ansible.builtin.meta: flush_handlers
