---

stages:
  - zsh
  - tools

debian_setup_zsh:
  stage: zsh
  image: ubuntu:20.04
  before_script:
    - echo Installing zsh on Debian
    - apt update && apt install -y git zsh
  script:
    - echo Setup zsh
    - bash setup-zsh.sh

rhel_setup_zsh:
  stage: zsh
  image: fedora:38
  before_script:
    - echo Installing zsh on RHEL
    - yum install -y git which util-linux-user zsh
  script:
    - echo Setup zsh
    - bash setup-zsh.sh

debian_setup_tools:
  stage: tools
  image: ubuntu:20.04
  before_script:
    - echo Installing packages on Debian
    # - bash install-tools.sh
  script:
    - echo Setup docker
    # - bash docker-setup.sh
    - echo Setup minikube
    # - bash setup-minikube.sh

rhel_setup_tools:
  stage: tools
  image: fedora:38
  before_script:
    - echo Installing packages on RHEL
    - bash install-tools.sh
  script:
    - echo Setup docker
    # - bash docker-setup.sh
    - echo Setup minikube
    # - bash setup-minikube.sh