debian_test:
  image: ubuntu:20.04
  before_script:
    - echo Before script step on DEBIAN
  script:
    - bash install-tools.sh

rhel_test:
  image: fedora:38
  before_script:
    - echo Before script step on RHEL
  script:
    - bash install-tools.sh