---

- name: Deploy Jellyfin node
  hosts: jellyfin_node
  become: true
  handlers:
    - import_tasks: tasks/handlers/main.yml
  tasks:
    - name: Import repositories tasks
      ansible.builtin.import_tasks: tasks/common/repositories.yml
      tags: jellyfin_node::repositories

    - name: Import packages tasks
      ansible.builtin.import_tasks: tasks/common/packages.yml
      tags: jellyfin_node::packages
    
    - name: Import shell tasks
      ansible.builtin.import_tasks: tasks/common/shell.yml
      tags: jellyfin_node::shell
  
    - name: Import jellyfin tasks
      ansible.builtin.import_tasks: tasks/common/jellyfin.yml
      tags: jellyfin_node::jellyfin
    
    - name: Import backup tasks
      ansible.builtin.import_tasks: tasks/common/restic.yml
      tags: jellyfin_node::backup
    
    - name: Configure and deploy glance agent
      ansible.builtin.import_tasks: tasks/common/glance-agent.yml
      tags: jellyfin_node::glance

    - name: Configure and deploy monitoring tools (node explorer for prometheus & promtail for loki)
      ansible.builtin.import_tasks: tasks/common/monitoring.yml
      tags: jellyfin_node::monitoring
