---

- name: Kubernetes Deploy
  hosts: k8s
  become: true
  handlers:
    - import_tasks: tasks/handlers/main.yml
  tasks:
    - name: "Setup System"
      ansible.builtin.import_tasks: tasks/k8s/01-system.yml
      tags: k8s::system
    
    - name: "Install Packages"
      ansible.builtin.import_tasks: tasks/k8s/02-packages.yml
      tags: k8s::packages
    
    - name: "Prepare filesystem"
      ansible.builtin.import_tasks: tasks/k8s/03-filesystem.yml
      when: inventory_hostname in groups['k8s_workers']
      tags: k8s::filesystem
    
    - name: "Setup kube-vip manifest"
      ansible.builtin.import_tasks: tasks/k8s/04-kube-vip.yml
      when: inventory_hostname in groups['k8s_controlplanes']
      tags: k8s::vip

    - name: "Init kubeadm"
      ansible.builtin.import_tasks: tasks/k8s/05-kubeadm-init.yml
      when: inventory_hostname in groups['k8s_controlplanes']
      tags: k8s::init
    
    - name: "Init kubeadm"
      ansible.builtin.import_tasks: tasks/k8s/06-cilium-cni.yml
      when: inventory_hostname == groups['k8s_controlplanes'][0]
      tags: k8s::cni
    
    - name: "Join nodes"
      ansible.builtin.import_tasks: tasks/k8s/07-join-nodes.yml
      tags: k8s::join
    
    - name: "Verify cluster"
      ansible.builtin.import_tasks: tasks/k8s/08-verify-cluster.yml
      when: inventory_hostname == groups['k8s_controlplanes'][0]
      tags: k8s::verify

    - name: "Bootstrap Flux"
      ansible.builtin.import_tasks: tasks/k8s/10-bootstrap-flux.yml
      when: inventory_hostname == groups['k8s_controlplanes'][0]
      tags: k8s::flux

