version: '3.8'

services:
  ubuntu_laptop:
    image: ubuntu:latest
    container_name: ubuntu_laptop
    tty: true
    networks:
      ansible:
        ipv4_address: 172.10.1.10
    command: >
      bash -c "echo 'tzdata tzdata/Areas select Europe' | debconf-set-selections &&
      echo 'tzdata tzdata/Zones/America select Paris' | debconf-set-selections &&
      DEBIAN_FRONTEND=noninteractive apt update &&
      DEBIAN_FRONTEND=noninteractive apt install -y tzdata &&
      apt update && apt install -y openssh-server sudo && 
      useradd -m test && echo 'test:test' | chpasswd && usermod -aG sudo test &&
      service ssh start && tail -f /dev/null"
  fedora_laptop:
    image: fedora:latest
    container_name: fedora_laptop
    tty: true
    networks:
      ansible:
        ipv4_address: 172.10.1.20
    command: >
      bash -c "dnf update -y && dnf install -y openssh-server && 
      useradd -m test && echo 'test:test' | chpasswd && usermod -aG wheel test &&
      ssh-keygen -A && /usr/sbin/sshd -D && tail -f /dev/null"
  debian_server:
    image: debian:latest
    container_name: debian_server
    tty: true
    networks:
      ansible:
        ipv4_address: 172.10.1.30
    command: >
      bash -c "apt update && apt install -y openssh-server sudo python3 && 
      useradd -m test && echo 'test:test' | chpasswd && usermod -aG sudo test &&
      service ssh start && tail -f /dev/null"
  raspberry_pi_os:
    image: bitnami/minideb:latest
    container_name: raspberry_pi_1
    tty: true
    networks:
      ansible:
        ipv4_address: 172.10.1.40
    command: >
      bash -c "apt update && apt install -y openssh-server sudo python3 &&
      useradd -m test && echo 'test:test' | chpasswd && usermod -aG sudo test &&
      service ssh start && tail -f /dev/null"

networks:
  ansible:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.1.0/24
