---

- name: Insure all required packages installing
  hosts: local
  become: true
  vars_files:
    - vars/local.yml
  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: latest

    - name: Install required packages
      package:
        name: "{{ packages_to_install }}"
        state: latest