---

- name: Install tools
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages_to_install }}"