Vagrant.configure("2") do |config|
    config.vm.define "jenkins-master" do |master|
      master.vm.provider "docker" do |docker|
        docker.image = "jenkins/jenkins:lts"
        docker.name = "jenkins-master"
        docker.ports = ["8080:8080"]
        docker.env = ["JENKINS_SLAVE_AGENT_PORT=50000"]
      end
      master.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../Ansible/jenkins.yml"
        ansible.inventory_path = "../../Ansible/inventories/jenkins"
      end
    end
  
    config.vm.define "jenkins-slave-1" do |slave1|
      slave1.vm.provider "docker" do |docker|
        docker.image = "jenkins/jnlp-slave"
        docker.name = "jenkins-slave-1"
      end
      slave1.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../Ansible/jenkins.yml"
        ansible.inventory_path = "../../Ansible/inventories/jenkins"
      end
    end
  
    config.vm.define "jenkins-slave-2" do |slave2|
      slave2.vm.provider "docker" do |docker|
        docker.image = "jenkins/jnlp-slave"
        docker.name = "jenkins-slave-2"
      end
      slave2.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../Ansible/jenkins.yml"
        ansible.inventory_path = "../../Ansible/inventories/jenkins"
      end
    end
  end
  