---

- name: Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Template keepalived config
  ansible.builtin.template:
    src: "network/keepalived/keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    enabled: true
    state: restarted
    