---

- name: Create Pi-hole config directory
  ansible.builtin.file:
    name: "/etc/pihole"
    state: directory

- name: Template Pi-hole config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ pihole_config_files }}"

- name: Download Pi-hole installer
  shell: "curl -sSL {{ pihole_installer_url }} -o /tmp/install_pihole.sh"
  args:
    creates: /tmp/install_pihole.sh

- name: Run Pi-hole installer non-interactively
  ansible.builtin.command: >
    bash /tmp/install_pihole.sh --unattended
  args:
    creates: "/etc/pihole/pihole.toml"

- name: Add custom dnsmasq lines to pihole.toml
  ansible.builtin.replace:
    path: /etc/pihole/pihole.toml
    regexp: '(?s)dnsmasq_lines\s*=\s*\[.*?\]'
    replace: |
      dnsmasq_lines = [
        "dhcp-option=6,{{ pihole_vip }}",
        "address=/{{ gateway_hostname }}/{{ lan_prefix }}.254",
        "address=/.{{ domain_name }}/{{ caddy_vip }}"
      ]

- name: Set pihole port to 80 HTTPS (free ports 443 and 80 for Caddy)
  ansible.builtin.lineinfile:
    path: /etc/pihole/pihole.toml
    regexp: '^\s*port = "80.*'
    line: '  port = "80o,[::]:80o"'
    backup: yes

- name: Set Pi-hole v6 password
  ansible.builtin.command: pihole setpassword "{{ pihole_password }}"

- name: Ensure Pi-hole FTL is restarted
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted
    enabled: true

- name: Add Pi-hole blocklists
  ansible.builtin.shell: >
    pihole-FTL sqlite3 /etc/pihole/gravity.db 
    "INSERT OR IGNORE INTO adlist (address, comment, enabled) VALUES ('{{ item.url }}', '{{ item.comment }}', 1);"
  loop: "{{ pihole_blocklists }}"

- name: Reload Pi-hole Gravity database
  ansible.builtin.command: pihole -g
