---

- name: Create PiVPN group
  ansible.builtin.group:
    name: pivpn
    system: true
    state: present

- name: Create PiVPN user
  ansible.builtin.user:
    name: pivpn
    group: pivpn
    shell: /bin/bash
    create_home: true
    home: /home/pivpn
    system: false
    state: present

- name: Ensure config dirs is created
  ansible.builtin.file: 
    path: "{{ item }}"
    state: directory
    owner: pivpn
    group: pivpn
  loop:
    - "/home/pivpn/configs"
    - "/etc/pivpn/wireguard"

- name: Template Pi-VPN config file
  ansible.builtin.template:
    src: "network/pivpn/setupVars.conf.j2"
    dest: "/etc/pivpn/wireguard/setupVars.conf"
    force: false

- name: Download Pi-VPN installer
  ansible.builtin.get_url:
    url: "https://install.pivpn.io"
    dest: /tmp/install_pivpn.sh
    mode: '0755'

- name: Run Pi-VPN installer non-interactively
  ansible.builtin.shell: >
    bash /tmp/install_pivpn.sh --unattended /etc/pivpn/wireguard/setupVars.conf
  args:
    creates: "/etc/wireguard/wg0.conf"

- name: Add WireGuard clients
  ansible.builtin.command: "pivpn -a -n {{ item.name }} -ip {{ item.vip }}"
  args:
    creates: "/home/pivpn/configs/{{ item.name }}.conf"
  loop: "{{ pivpn_wireguard_clients }}"
  when: inventory_hostname == 'raspberry'

# ── MASTER → BACKUP SYNC ───────────────────────────────────────────────────────
- name: Sync WireGuard and PiVPN configs from master to backup
  when: inventory_hostname == 'raspberry_backup'
  block:
    - name: Find all files in source directories
      ansible.builtin.find:
        paths: 
          - "/etc/wireguard"
          - "/home/pivpn/configs"
        recurse: yes
      delegate_to: raspberry
      register: found_files

    - name: Ensure directories exist on raspberry_backup
      ansible.builtin.file:
        path: "{{ item.path | dirname }}"
        state: directory
        owner: "{{ item.pw_name }}"
        group: "{{ item.gr_name }}"
        mode: "{{ item.mode | default('0755') }}"
      loop: "{{ found_files.files }}"

    - name: Read file content from raspberry
      ansible.builtin.slurp:
        src: "{{ item.path }}"
      delegate_to: raspberry
      loop: "{{ found_files.files }}"
      register: remote_content

    - name: Write content to raspberry_backup
      ansible.builtin.copy:
        content: "{{ item.content | b64decode }}"
        dest: "{{ item.source }}"
        owner: "{{ item.pw_name | default('root') }}"
        group: "{{ item.gr_name | default('root') }}"
        mode: "{{ item.mode | default('0644') }}"
      loop: "{{ remote_content.results }}"

- name: Reload new configs
  block:
    - name: Run pivpn debug
      ansible.builtin.shell: "Y | pivpn -d"
    - name: Restart wireguard service
      ansible.builtin.service:
        name: wg-quick@wg0
        state: restarted
        enabled: true
