---

- name: Create directories
  ansible.builtin.file:
    name: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  loop: "{{ directories }}"

- name: Remove directories
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop: "{{ directories_to_remove }}"