---

- name: Create disk partitions
  community.general.parted:
    device: "{{ item.device }}"
    number: "{{ item.partition_number }}"
    flags: "{{ item.flags }}"
    part_start: "{{ item.part_start }}"
    part_end: "{{ item.part_end }}"
    state: present
  loop: "{{ disk_partitions }}"
  
- name: Create physical volumes and volume groups
  community.general.lvg:
    vg: "{{ item.vg }}"
    pvs: "{{ item.pvs }}"
    state: present
  loop: "{{ disk_vgs }}"

- name: Create logical volumes
  community.general.lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.lv }}"
    size: "{{ item.size }}"
    state: present
  loop: "{{ disk_lvs }}"

- name: Format logical volumes
  ansible.builtin.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "/dev/{{ item.vg }}/{{ item.lv }}"
  loop: "{{ disk_lvs }}"

- name: Mount points and directories
  block:
    - name: Create mount points
      ansible.builtin.file:
        name: "{{ item.mount_point }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
      loop: "{{ disk_lvs }}"

    - name: Create directories
      ansible.builtin.file:
        name: "{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
      loop: "{{ directories }}"

- name: Mount logical volumes to mount points
  ansible.builtin.mount:
    path: "{{ item.mount_point }}"
    src: "/dev/{{ item.vg }}/{{ item.lv }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop: "{{ disk_lvs }}"

- name: Persist the mount in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/dev/{{ item.vg }}/{{ item.lv }} {{ item.mount_point }} {{ item.fstype }} defaults 0 0"
    state: present
  loop: "{{ disk_lvs }}"