---


- name: Mount logical volumes
  ansible.posix.mount:
    path: "{{ item.mount_point }}"
    src: "/dev/{{ item.vg }}/{{ item.lv }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop: "{{ disk_lvs }}"

- name: Create directories
  ansible.builtin.file:
    name: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  loop: "{{ directories }}"