---

- name: Install system packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Install python packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ python_packages }}"