---

- name: Install rclone
  ansible.builtin.apt:
    deb: "{{ rclone_package }}"

- name: Setup rclone configs
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: '{{ rclone_config_location | dirname }}'
        state: directory
        owner: '{{ rclone_config_owner.OWNER }}'
        group: '{{ rclone_config_owner.GROUP }}'
        mode: '0755'
    
    - name: Set up rclone config
      ansible.builtin.template:
        src: rclone/rclone.conf.j2
        owner: '{{ rclone_config_owner.OWNER }}'
        group: '{{ rclone_config_owner.GROUP }}'
        dest: '{{ rclone_config_location }}'
        mode: 0600

- name: Ensure rclone remote directory exists
  ansible.builtin.command:
    cmd: "rclone mkdir '{{ item.remote_name }}':{{ item.remote_path }}"
  loop: "{{ rclone_mounts }}"
  when:
    - item.remote_path != '/'
  register: rclone_mkdir_output
  changed_when: rclone_mkdir_output.rc == 0

- name: Ensure local path exists
  block:
    - name: Unmount directory if already mounted
      ansible.builtin.command: "umount {{ item.local_path }}"
      loop: "{{ rclone_mounts }}"
      ignore_errors: yes # Prevent failure if it's not mounted
    
    - name: Ensure directory exists
      ansible.builtin.file:
        path: "{{ item.local_path }}"
        mode: "{{ item.local_path_mode }}"
        owner: "{{ item.local_path_owner }}"
        group: "{{ item.local_path_group }}"
        state: directory
      loop: "{{ rclone_mounts }}"

- name: Uncomment "user_allow_other" or add it if missing
  ansible.builtin.lineinfile:
    path: /etc/fuse.conf
    regexp: '^#?(user_allow_other)'
    line: 'user_allow_other'
    backrefs: yes
    state: present

- name: Create and activate services rclone mount
  ansible.builtin.template:
    src: rclone/rclone-mount@.service.j2
    dest: "/etc/systemd/system/rclone-mount@{{ item.name | replace(' ', '_') }}.service"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ rclone_mounts }}"

- name: Enable and restart rclone-mount services
  ansible.builtin.systemd:
    name: "rclone-mount@{{ item.name | replace(' ', '_') }}.service"
    enabled: yes
    daemon_reload: yes
    state: restarted
  loop: "{{ rclone_mounts }}"
