---

authelia_domains_policy:
  - domain: "grafana.{{ domain_name }}"
    policy: "bypass"
  - domain: "jellyfin.{{ domain_name }}"
    policy: "bypass"
  - domain: "cloud.{{ domain_name }}"
    policy: "bypass"
  - domain: "portainer.{{ domain_name }}"
    policy: "bypass"
  - domain: "vault.{{ domain_name }}"
    policy: "bypass"
  - domain: "jellyfin.{{ domain_name }}"
    policy: "bypass"
  - domain: "dash.{{ domain_name }}"
    policy: "bypass"
  - domain: "torrent.{{ domain_name }}"
    policy: "bypass"
  - domain: "jellyseerr.media.{{ domain_name }}"
    policy: "bypass"
  - domain: "*.{{ domain_name }}"
    policy: "one_factor"
authelia_oidc_clients:
  - id: "grafana"
    description: "Grafana"
    secret: "{{ authelia_oidc_clients_secrets.grafana.secret }}"
    public: false
    authorization_policy: "two_factor"
    redirect_uris:
      - "https://grafana.{{ domain_name }}"
    scopes:
      - "openid"
      - "profile"
      - "groups"
      - "email"
    userinfo_signing_algorithm: "none"
  - id: "homarr"
    description: "Homarr"
    secret: "{{ authelia_oidc_clients_secrets.homarr.secret }}"
    public: false
    authorization_policy: "two_factor"
    redirect_uris:
      - "https://dash.{{ domain_name }}"
    scopes:
      - "openid"
      - "profile"
      - "groups"
      - "email"
    userinfo_signing_algorithm: "none"  
  - id: "jellyfin"
    description: "Jellyfin"
    secret: "{{ authelia_oidc_clients_secrets.jellyfin.secret }}"
    public: false
    authorization_policy: "two_factor"
    redirect_uris:
      - "https://jellyfin.{{ domain_name }}"
    scopes:
      - "openid"
      - "profile"
      - "groups"
      - "email"
    userinfo_signing_algorithm: "none"
  - id: "nextcloud"
    description: "Nextcloud"
    secret: "{{ authelia_oidc_clients_secrets.nextcloud.secret }}"
    public: false
    authorization_policy: "two_factor"
    redirect_uris:
      - "https://cloud.{{ domain_name }}"
    scopes:
      - "openid"
      - "profile"
      - "groups"
      - "email"
    userinfo_signing_algorithm: "none"
  - id: "portainer"
    description: "Portainer"
    secret: "{{ authelia_oidc_clients_secrets.portainer.secret }}"
    public: false
    authorization_policy: "two_factor"
    redirect_uris:
      - "https://portainer.{{ domain_name }}"
    scopes:
      - "openid"
      - "profile"
      - "groups"
      - "email"
    userinfo_signing_algorithm: "none"
  - id: "vaultwarden"
    description: "Vaultwarden"
    secret: "{{ authelia_oidc_clients_secrets.vaultwarden.secret }}"
    public: false
    authorization_policy: "two_factor"
    redirect_uris:
      - "https://vault.{{ domain_name }}"
    scopes:
      - "openid"
      - "profile"
      - "groups"
      - "email"
    userinfo_signing_algorithm: "none"

common_deb_packages:
  - "{{ rclone_package }}"

common_directories:
  - "{{ zsh_directory }}"
  - "{{ docker_services_directory }}"
  - "{{ scripts_directory }}"

common_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - coreutils
  - curl
  - gnupg2
  - git
  - jq
  - lsb-release
  - openssl
  - python3-pip
  - restic
  - software-properties-common
  - unzip
  - vim
  - wget

common_rclone_configs: 
  - name: "mega"
    properties:
      type: "mega"
      user: "{{ mega_username }}"
      pass: "{{ mega_encpassword }}"
  - name: "protondrive"
    properties:
      type: "protondrive"
      username: "{{ proton_username }}"
      password: "{{ proton_encpassword }}"
      2fa: "{{ proton_2fa }}"


common_rclone_mounts:
  - name: "mega"
    remote_name: "mega" 
    remote_path: "/"
    local_path: "/mnt/mega"
    local_path_mode: '0755'
    local_path_owner: "{{ rclone_config_owner.OWNER }}"
    local_path_group: "{{ rclone_config_owner.GROUP }}"
    auto_mount: true
    extra_args: "--allow-other"
  - name: "protondrive"
    remote_name: "protondrive" 
    remote_path: "/"
    local_path: "/mnt/protondrive"
    local_path_mode: '0755'
    local_path_owner: "{{ rclone_config_owner.OWNER }}"
    local_path_group: "{{ rclone_config_owner.GROUP }}"
    auto_mount: true
    extra_args: "--allow-other"

config_files:
  - file: .secrets
    dest_path: "{{ user_home }}"
    mode: '0600'
  - file: .zshrc
    dest_path: "{{ user_home }}"
    mode: '0644'
  - file: .p10k.zsh
    dest_path: "{{ zsh_directory }}"
    mode: '0644'

docker_services_directory: /opt/docker_services

docker_packages:
  - docker-ce 
  - docker-ce-cli
  - containerd.io 
  - docker-compose
  - docker-buildx-plugin 
  - docker-compose-plugin

documents_directory: "{{ user_home }}/Documents"

postgres_host: "{{ ansible_facts.lo.ipv4.address }}"

purge_all: no

purge_vars:
  docker: no
  packages: no
  repositories: no
  shell: no
  services: no

rclone_config_location: "/root/.config/rclone/rclone.conf"

rclone_config_owner:
  OWNER: "{{ rclone_user }}"
  GROUP: "{{ rclone_user }}"

rclone_package: "https://downloads.rclone.org/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-amd64.deb"

rclone_user: "root"

rclone_version: 1.69.1

restic_env_vars:
  RESTIC_PASSWORD: "{{ restic_password }}"
restic_logs_directory: "/var/log/restic"
restic_remote: "rclone:protondrive"
restic_remote_verify_command: "rclone lsf protondrive:"
restic_scripts_directory: "{{ scripts_directory }}/restic"

scripts_directory: "/opt/scripts"

timezone: "Europe/Paris"

user_home: "/home/{{ ansible_user }}"

zsh_directory: "{{ user_home }}/.zsh"

zsh_packages:
  - zsh

zsh_repositories:
  - repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_directory }}/powerlevel10k"
    depth: 1
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_directory }}/plugins/zsh-syntax-highlighting"
    depth: 0
  - repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_directory }}/plugins/zsh-autosuggestions"
    depth: 0
