---

glance_agent_package: "agent-linux-{{ arch }}"
glance_agent_archive_url: "https://github.com/glanceapp/agent/releases/download/v0.1.0/{{ glance_agent_package }}.tar.gz"

loki_url: "https://loki.{{ domain_name }}"

node_exporter_archive_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_package }}"
node_exporter_systemd_service:
  - name: "node_exporter"
    unit_properties:
      Description: "Node Exporter service for Prometheus monitoring"
      Wants: "network-online.target"
      After: "network-online.target"
    service_properties:
      Type: "simple"
      ExecStart: "/usr/local/bin/node_exporter"
      User: "{{ node_exporter_service_user }}"
      Group: "{{ node_exporter_service_user }}"
    install_properties:
      WantedBy: "default.target"

node_exporter_package: "node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
node_exporter_version: "1.9.1"

promtail_binary: "/usr/local/bin/promtail"
promtail_package: "promtail_{{ promtail_version }}_{{ arch }}.deb"
promtail_package_url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/{{ promtail_package }}"
promtail_version: "3.4.4"