---

repositories:
  - name: "jellyfin"
    repo_url: "https://repo.jellyfin.org/ubuntu"
    gpg_url: "https://repo.jellyfin.org/jellyfin_team.gpg.key"
    gpg_extention: "gpg"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "main"

extra_packages:
  - jellyfin
  - mesa-va-drivers
  - vainfo

packages: "{{ common_packages + extra_packages }}"

user_home: "/root"

restic_backup_configs:
  - name: "jellyfin"
    dir_to_backup: 
      - "/etc/jellyfin"
      - "/var/lib/jellyfin"
    local_backup_repo: "{{ backup_mount }}"
    remote_backup_repo: "{{ restic_remote }}:jellyfin_backup"
    cron:
      hour: "10"
      minute: "0"

glance_mountpoints_to_monitor:
  - name: "Root"
    path: "/"

node_exporter_service_user: "root"

promtail_instance: "jellyfin_node"
