---

- name: Create directories
  block:
    - name: Ensure directories are created
      ansible.builtin.file:
        name: "{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
      loop: "{{ directories }}"
      tags: create::directories