---

- name: Add GPG keys
  ansible.builtin.get_url:
    url: "{{ item.gpg_url }}"
    dest: "/etc/apt/trusted.gpg.d/{{ item.name }}.{{ item.gpg_extention }}"
  loop: "{{ repositories }}"

- name: Add APT repositories
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/{{ item.name }}.{{ item.gpg_extention }}] {{ item.repo_url }} {{ item.components | join(' ') }}"
    filename: "{{ item.name }}-archive"
    state: present
  loop: "{{ repositories }}"

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600