---

- name: Purge services
  block:
    - name: Stop services
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: stopped
      loop: "{{ systemd_services }}"

    - name: Remove services files
      ansible.builtin.file:
        name: "/etc/systemd/system/{{ item.name }}.service"
        state: absent
      loop: "{{ systemd_services }}"
  when: purge_vars.services
  tags: purge::services

- name: Configure and start services
  block:
    - name: Create systemd services files
      ansible.builtin.template:
        src: systemd_service.j2
        dest: "/etc/systemd/system/{{ service.name }}.service"
      loop: "{{ systemd_services }}"
      loop_control:
        loop_var: service

    - name: Enable and start services
      ansible.builtin.systemd:
        name: "{{ item.name }}"
        daemon_reload: yes
        enabled: yes
        state: restarted
      loop: "{{ systemd_services }}"
  tags: create::services