---

extra_packages:
  - unbound
  - keepalived
  - wireguard 
  - wireguard-tools
  - qrencode
  - "linux-headers-{{ arch }}"

deb_packages:
  - "{{ promtail_package_url }}"

packages: "{{ common_packages + extra_packages }}"

glance_mountpoints_to_monitor:
  - name: "Root"
    path: "/"
