---

- name: Add GPG keys (Dearmored)
  shell: |
    curl -fsSL {{ item.gpg_url }} | gpg --dearmor -o /usr/share/keyrings/{{ item.name }}.gpg
  args:
    creates: "/usr/share/keyrings/{{ item.name }}.gpg"
  loop: "{{ repositories }}"

- name: Add APT repositories
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/{{ item.name }}.gpg] {{ item.repo_url }} {{ item.components | join(' ') }}"
    filename: "{{ item.name }}-archive"
    state: present
  loop: "{{ repositories }}"
  notify: "Update APT cache"

- name: Run the handler
  ansible.builtin.meta: flush_handlers