---

repositories:
  - repo: "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    repo_list_file: "/etc/apt/sources.list.d/vscode.list"
    gpg_url: "https://packages.microsoft.com/keys/microsoft.asc"
    gpg_keyring: "/etc/apt/keyrings/microsoft.gpg"

extra_packages:
  - openjdk-17-jdk
  
packages_to_install: "{{ base_packages + extra_packages }}"