---

- name: Debug var
  hosts: workstations
  tasks:
    - name: Display the var to debug     
      ansible.builtin.debug:
        msg: "Variable to debug: {{ lookup('community.general.bitwarden', 'postgres_service', field='database') | first }} | first }}"