- name: Test template
  hosts: workstations
  vars:
    workstations_docker_services:
      - name: "homarr"
        services:
          - name: "homarr"
            image: "ghcr.io/homarr-labs/homarr:v1.6.0"
            volumes:
              - "./data:/appdata"
              - "/var/run/docker.sock:/var/run/docker.sock"
            environment:
              - "SECRET_ENCRYPTION_KEY=homarr_sec"
            restart: "unless-stopped"
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.homarr.tls=true"
              - "traefik.http.routers.homarr.tls.certresolver=cloudflare"
              - "traefik.http.routers.homarr.rule=Host(`homarr.domain.com`)"
              - "traefik.http.services.homarr.loadbalancer.server.port=7575"
            networks:
              - frontend
          - name: "grafana"
            image: "grafana/grafana:latest"
            volumes:
              - "./data/grafana/:/var/lib/grafana"
            restart: "unless-stopped"
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.grafana.tls=true"
              - "traefik.http.routers.grafana.tls.certresolver=cloudflare"
              - "traefik.http.routers.grafana.rule=Host(`grafana.domain.com`)"
              - "traefik.http.services.grafana.loadbalancer.server.port=3000"
            networks:
              - frontend
              - backend
        networks:
          - name: "frontend"
            external: true
  tasks:
    - name: Template   
      ansible.builtin.template:
        src: "../../templates/test.j2"
        dest: "/home/yacin/docker-compose-test.yml"
      loop: "{{ workstations_docker_services }}"
      loop_control:
        loop_var: stack