---

glance_mountpoints_to_monitor:
  - name: "Root"
    path: "/"
  - name: "Media"
    path: "/data-zfs/media"
  - name: "Proxmox"
    path: "/data-zfs/proxmox"
  - name: "Backup"
    path: "/data-zfs/backup"

node_exporter_service_user: "root"

promtail_instance: "proxmox"
