---

cilium_version: 1.16.4

k8s_packages:
  - kubelet
  - kubeadm
  - kubectl
  - containerd
  - cryptsetup
  - conntrack
  - socat
  - ebtables
  - ethtool

k8s_vip: "{{ lan_prefix }}.30"
k8s_interface: eth0

kubevip_version: "v1.1.1"

repositories:
  - name: "k8s"
    apt:
      repo_url: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/"
      gpg_url: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key"
      components:
        - "/"