---

backup_directory: "{{ user_home }}/Backups"

common_docker_networks: []

common_docker_services: []

common_docker_services_configs: []

common_docker_services_crons: []

common_directories:
  - "{{ zsh_directory }}"
  - "{{ docker_services_directory }}"

common_directories_to_remove: []

common_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - coreutils
  - curl
  - gnupg2
  - git
  - jq
  - lsb-release
  - openssl
  - python3-pip
  - software-properties-common
  - unzip
  - vim
  - wget

common_python_packages: []

common_repositories: []

common_systemd_services: []

config_files:
  - file: .vimrc
    dest_path: "{{ user_home }}"
    mode: '0644'
  - file: .secrets
    dest_path: "{{ user_home }}"
    mode: '0600'
  - file: .zshrc
    dest_path: "{{ user_home }}"
    mode: '0644'
  - file: .p10k.zsh
    dest_path: "{{ zsh_directory }}"
    mode: '0644'

docker_services_directory: /opt/docker_services

docker_packages:
  - docker-ce 
  - docker-ce-cli
  - containerd.io 
  - docker-compose
  - docker-buildx-plugin 
  - docker-compose-plugin

documents_directory: "{{ user_home }}/Documents"

postgres_host: "{{ ansible_facts.lo.ipv4.address }}"

purge_all: no

purge_vars:
  docker: no
  packages: no
  repositories: no
  shell: no
  services: no

timezone: "Europe/Paris"

user_home: "/home/{{ ansible_user }}"

zsh_directory: "{{ user_home }}/.zsh"

zsh_packages:
  - zsh

zsh_repositories:
  - repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_directory }}/powerlevel10k"
    depth: 1
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_directory }}/plugins/zsh-syntax-highlighting"
    depth: 0
  - repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_directory }}/plugins/zsh-autosuggestions"
    depth: 0
