---

server_docker_networks:
  - frontend
  - backend

server_docker_services:
  # - name: "homepage"
  - name: "seafile"
    services:
      - name: "seafile-app"
        image: "seafileltd/seafile-mc:12.0-latest"
        volumes:
          - "./data/app:/var/www/html"
        depends_on:
          - "seafile-db"
          - "seafile-memcached"
        environment:
          - "DB_HOST=seafile-db"
          - "DB_ROOT_PASSWD={{ seafile_db_root_password }}"
          - "INIT_SEAFILE_ADMIN_EMAIL={{ seafile_admin_email }}"
          - "INIT_SEAFILE_ADMIN_PASSWORD={{ seafile_admin_password }}"
          - "SEAFILE_SERVER_HOSTNAME=seafile.{{ traefik_domain_name }}"
          - "SEAFILE_SERVER_PROTOCOL=https"
          - "JWT_PRIVATE_KEY={{ seafile_jwt_private_key }}"
        restart: "unless-stopped"
        networks:
          - "frontend"
          - "backend"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.seafile.tls=true"
          - "traefik.http.routers.seafile.tls.certresolver=cloudflare"
          - "traefik.http.routers.seafile.rule=Host(`seafile.{{ traefik_domain_name }}`)"
          - "traefik.docker.network=frontend"
      - name: "seafile-db"
        image: "mariadb:10"
        volumes:
          - "./data/db:/var/lib/mysql"
        environment:
          - "MYSQL_ROOT_PASSWORD={{ seafile_db_root_password }}"
        restart: "unless-stopped"
        networks:
          - "backend"
      - name: "seafile-memcached"
        image: "memcached:1"
        entrypoint: memcached -m 256
        restart: "unless-stopped"
        networks:
          - "backend"
    networks:
      - name: "frontend"
        external: true
      - name: "backend"
        external: true
  
  - name: "immich"
    services:
      - name: "immich-server"
        image: "ghcr.io/immich-app/immich-server:v1.125.7"
        volumes:
          - "./data/upload:/usr/src/app/upload"
          - "/etc/localtime:/etc/localtime:ro"
        environment:
          - "DB_PASSWORD={{ immich_db_password }}"
          - "DB_USERNAME={{ immich_db_user }}"
          - "DB_DATABASE_NAME={{ immich_db }}"
        depends_on:
          - "redis"
          - "database"
        restart: "unless-stopped"
        healthcheck:
          disable: false
        networks:
          - "frontend"
          - "backend"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.immich.tls=true"
          - "traefik.http.routers.immich.tls.certresolver=cloudflare"
          - "traefik.http.routers.immich.rule=Host(`immich.{{ traefik_domain_name }}`)"
          - "traefik.http.services.immich.loadbalancer.server.port=2283"
          - "traefik.docker.network=frontend"
      - name: "immich-machine-learning"
        image: "ghcr.io/immich-app/immich-machine-learning:v1.125.7"
        volumes:
          - "./data/model-cache:/cache"
        restart: "unless-stopped"
        healthcheck:
          disable: false
        networks:
          - "backend"
      - name: "redis"
        image: "redis:6"
        restart: "unless-stopped"
        healthcheck:
          test: redis-cli ping || exit 1
        networks:
          - "backend"
      - name: "database"
        image: "tensorchord/pgvecto-rs:pg14-v0.2.1"
        volumes:
          - "./data/db:/var/lib/postgresql/data"
        restart: "unless-stopped"
        environment:
          - "POSTGRES_PASSWORD={{ immich_db_password }}"
          - "POSTGRES_USER={{ immich_db_user }}"
          - "POSTGRES_DB={{ immich_db }}"
          - "POSTGRES_INITDB_ARGS=--data-checksums"
        command: >-
          postgres
          -c shared_preload_libraries=vectors.so
          -c 'search_path="$$user", public, vectors'
          -c logging_collector=on
          -c max_wal_size=2GB
          -c shared_buffers=512MB
          -c wal_compression=on
        healthcheck:
          test: >-
            pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
            Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
            --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
            echo "checksum failure count is $$Chksum";
            [ "$$Chksum" = '0' ] || exit 1
          interval: "5m"
          start_interval: "30s"
          start_period: "5m"
        networks:
          - "backend"
    networks:
      - name: "frontend"
        external: true
      - name: "backend"
        external: true
  
  - name: "nextcloud"
    services:
      - name: "nextcloud-app"
        image: "nextcloud:30"
        volumes:
          - "./data/app:/var/www/html"
        depends_on:
          - "nextcloud-redis"
          - "nextcloud-db"
        environment:
          - "MYSQL_HOST=nextcloud-db"
          - "MYSQL_PASSWORD={{ nextcloud_db_password }}"
          - "MYSQL_DATABASE={{ nextcloud_db }}"
          - "MYSQL_USER={{ nextcloud_db_user }}"
          - "REDIS_HOST=nextcloud-redis"
          - "TRUSTED_PROXIES=192.168.1.20"
          - "OVERWRITECLIURL=https://nextcloud.{{ traefik_domain_name }}"
          - "OVERWRITEWEBROOT=https"
        restart: "unless-stopped"
        networks:
          - "frontend"
          - "backend"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextcloud.tls=true"
          - "traefik.http.routers.nextcloud.tls.certresolver=cloudflare"
          - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.{{ traefik_domain_name }}`)"
          - "traefik.docker.network=frontend"
      - name: "nextcloud-redis"
        image: "redis:6"
        restart: "unless-stopped"
        healthcheck:
          test: redis-cli ping || exit 1
        networks:
          - "backend"
      - name: "nextcloud-db"
        image: "mariadb:10"
        volumes:
          - "./data/db:/var/lib/mysql"
        command: "--transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW"
        environment:
          - "MYSQL_ROOT_PASSWORD={{ nextcloud_root_db_password }}"
          - "MYSQL_PASSWORD={{ nextcloud_db_password }}"
          - "MYSQL_DATABASE={{ nextcloud_db }}"
          - "MYSQL_USER={{ nextcloud_db_user }}"
        restart: "unless-stopped"
        networks:
          - "backend"
    networks:
      - name: "frontend"
        external: true
      - name: "backend"
        external: true

  - name: "portainer"
    services:
      - name: "portainer"
        image: "portainer/portainer-ce:latest"
        volumes:
          - "./data:/data"
          - "/var/run/docker.sock:/var/run/docker.sock"
        restart: "unless-stopped"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.portainer.tls=true"
          - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
          - "traefik.http.routers.portainer.rule=Host(`portainer.{{ traefik_domain_name }}`)"
          - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        networks:
          - frontend
    networks:
      - name: "frontend"
        external: true
    
  - name: "traefik"
    services:
      - name: "traefik"
        image: "traefik:v3"
        volumes:
          - "./config/ssl:/ssl:rw"
          - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        restart: "unless-stopped"
        environment:
          - "CF_DNS_API_TOKEN={{ traefik_dns_api_token }}"
        networks:
          - frontend
      - name: "whoami"
        image: "traefik/whoami"
        restart: "unless-stopped"
        networks:
          - frontend
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.whoami.tls=true"
          - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
          - "traefik.http.routers.whoami.rule=Host(`whoami.{{ traefik_domain_name }}`)"
    networks:
      - name: "frontend"
        external: true

  - name: "postgres"
    services:
      - name: "postgres_db"
        image: "postgres:latest"
        environment:
          - "POSTGRES_DB={{ postgres_db }}"
          - "POSTGRES_USER={{ postgres_db_user }}"
          - "POSTGRES_PASSWORD={{ postgres_db_password }}"
        volumes:
          - "./data:/var/lib/postgresql/data"
        ports:
          - "5432:5432"
        networks:
          - "backend"
        restart: "unless-stopped"
    networks:
      - name: "backend"
        external: true
        
server_docker_services_configs:
  - src: "templates/traefik/config/traefik.yml.j2"
    dest: "{{ docker_services_directory }}/traefik/config/traefik.yml"

server_directories: []

server_directories_to_remove: []

server_packages:
  - python3-psycopg2
  - syncthing

server_python_packages: []

server_repositories:
  - name: "docker"
    repo_url: "https://download.docker.com/linux/debian"
    gpg_url: "https://download.docker.com/linux/debian/gpg"
    gpg_extention: "asc"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "stable"

server_systemd_services: []