---

server_docker_services: []

server_directories: []

server_directories_to_remove: []

server_packages: 
  - syncthing

server_python_packages: []

server_repositories:
  - name: "docker"
    repo_url: "https://download.docker.com/linux/debian"
    gpg_url: "https://download.docker.com/linux/debian/gpg"
    gpg_extention: "asc"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "stable"

server_systemd_services: []