---

# common_docker_networks: []

workstation_docker_networks:
  - frontend
  - backend

# workstation_docker_services: []

workstation_docker_services:
  # - name: "homepage"
  - name: "seafile"
    services:
      - name: "seafile-app"
        image: "seafileltd/seafile-mc:12.0-latest"
        volumes:
          - "./data/app:/var/www/html"
        depends_on:
          - "seafile-db"
          - "seafile-memcached"
        environment:
          - "DB_HOST=seafile-db"
          - "DB_ROOT_PASSWD={{ seafile_db_root_password }}"
          - "INIT_SEAFILE_ADMIN_EMAIL={{ seafile_admin_email }}"
          - "INIT_SEAFILE_ADMIN_PASSWORD={{ seafile_admin_password }}"
          - "SEAFILE_SERVER_HOSTNAME=seafile.{{ traefik_domain_name }}"
          - "SEAFILE_SERVER_PROTOCOL=https"
          - "JWT_PRIVATE_KEY={{ seafile_jwt_private_key }}"
        restart: "unless-stopped"
        networks:
          - "frontend"
          - "backend"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.seafile.tls=true"
          - "traefik.http.routers.seafile.tls.certresolver=cloudflare"
          - "traefik.http.routers.seafile.rule=Host(`seafile.{{ traefik_domain_name }}`)"
          - "traefik.docker.network=frontend"
      - name: "seafile-db"
        image: "mariadb:10"
        volumes:
          - "./data/db:/var/lib/mysql"
        environment:
          - "MYSQL_ROOT_PASSWORD={{ seafile_db_root_password }}"
        restart: "unless-stopped"
        networks:
          - "backend"
      - name: "seafile-memcached"
        image: "memcached:1"
        entrypoint: memcached -m 256
        restart: "unless-stopped"
        networks:
          - "backend"
    networks:
      - name: "frontend"
        external: true
      - name: "backend"
        external: true
  # - name: "immich"  
  - name: "nextcloud"
    services:
      - name: "nextcloud-app"
        image: "nextcloud:30"
        volumes:
          - "./data/app:/var/www/html"
        depends_on:
          - "nextcloud-db"
        environment:
          - "MYSQL_HOST=nextcloud-db"
          - "MYSQL_PASSWORD={{ nextcloud_db_password }}"
          - "MYSQL_DATABASE={{ nextcloud_db }}"
          - "MYSQL_USER={{ nextcloud_db_user }}"
        restart: "unless-stopped"
        networks:
          - "frontend"
          - "backend"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nextcloud.tls=true"
          - "traefik.http.routers.nextcloud.tls.certresolver=cloudflare"
          - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.{{ traefik_domain_name }}`)"
          - "traefik.docker.network=frontend"
      - name: "nextcloud-db"
        image: "mariadb:10"
        volumes:
          - "./data/db:/var/lib/mysql"
        command: "--transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW"
        environment:
          - "MYSQL_ROOT_PASSWORD={{ nextcloud_root_db_password }}"
          - "MYSQL_PASSWORD={{ nextcloud_db_password }}"
          - "MYSQL_DATABASE={{ nextcloud_db }}"
          - "MYSQL_USER={{ nextcloud_db_user }}"
        restart: "unless-stopped"
        networks:
          - "backend"
    networks:
      - name: "frontend"
        external: true
      - name: "backend"
        external: true

  - name: "portainer"
    services:
      - name: "portainer"
        image: "portainer/portainer-ce:latest"
        volumes:
          - "./data:/data"
          - "/var/run/docker.sock:/var/run/docker.sock"
        restart: "unless-stopped"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.portainer.tls=true"
          - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
          - "traefik.http.routers.portainer.rule=Host(`portainer.{{ traefik_domain_name }}`)"
          - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        networks:
          - frontend
    networks:
      - name: "frontend"
        external: true
    
  - name: "traefik"
    services:
      - name: "traefik"
        image: "traefik:v3"
        volumes:
          - "./config/ssl:/ssl:rw"
          - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        restart: "unless-stopped"
        environment:
          - "CF_DNS_API_TOKEN={{ traefik_dns_api_token }}"
        networks:
          - frontend
      - name: "whoami"
        image: "traefik/whoami"
        restart: "unless-stopped"
        networks:
          - frontend
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.whoami.tls=true"
          - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
          - "traefik.http.routers.whoami.rule=Host(`whoami.{{ traefik_domain_name }}`)"
    networks:
      - name: "frontend"
        external: true
  

# workstation_docker_services_configs: []
workstation_docker_services_configs:
  - src: "templates/traefik/config/traefik.yml.j2"
    dest: "{{ docker_services_directory }}/traefik/config/traefik.yml"

workstation_directories: []

workstation_directories_to_remove: []

workstation_packages: 
  - brave-browser
  - code
  - openjdk-17-jdk
  - python3-psycopg2
  - syncthing
  - virtualbox-7.1

workstation_python_packages: []

workstation_repositories:
  - name: "docker"
    repo_url: "https://download.docker.com/linux/ubuntu"
    gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    gpg_extention: "asc"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "stable"

  - name: "brave"
    repo_url: "https://brave-browser-apt-release.s3.brave.com"
    gpg_url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
    gpg_extention: "gpg"
    components:
      - "stable"
      - "main"

  - name: "vscode"
    repo_url: "https://packages.microsoft.com/repos/code"
    gpg_url: "https://packages.microsoft.com/keys/microsoft.asc"
    gpg_extention: "asc"
    components:
      - "stable"
      - "main"

  - name: "virtualbox"
    repo_url: "https://download.virtualbox.org/virtualbox/debian"
    gpg_url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    gpg_extention: "asc"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "contrib"

workstation_systemd_services: []

