# https://github.com/glanceapp/community-widgets/blob/main/widgets/gluetun-vpn-status/README.md
- type: custom-api
  title: Media VPN Status
  cache: 1m
  url: ${MEDIA_GLUETUN_URL}/v1/publicip/ip
  headers:
    X-API-Key: ${MEDIA_GLUETUN_KEY}
  template: |
    {{ if eq .Response.StatusCode 200 }}
      {{ $ip := (.JSON.String "public_ip") }}
      {{ $city := (.JSON.String "city") }}
      {{ $country := (.JSON.String "country") }}
      {{ if eq $ip "" }}
        <div>
          <div>
            <div>
              <div class="color-highlight size-h3">
                Your VPN is not connected!
                <span class="color-negative">●</span> 
              </div>
            </dv>
          </div>
        </div>
      {{ else }}
        <div>
          <div>
            <div>
              <div class="color-highlight size-h3">
                Your VPN is connected!
                <span class="color-positive">●</span> 
              </div>
            </div>
            <div class="size-h5">{{ $ip }} - {{ $city }}, {{ $country }}</div>
          </div>
        </div>
      {{ end }}
    {{ else }}
      <div style="text-align: center; color: var(--color-negative);">
        Error: {{ .Response.StatusCode }} - {{ .Response.Status }}
      </div>
    {{ end }}