---

- name: Purge Zsh
  hosts: all
  become: yes
  pre_tasks:
    - name: Skip play if purge is disabled
      ansible.builtin.meta: end_play
      when: not purge_vars.shell
  tasks:
    - name: Remove zsh themes and plugins
      ansible.builtin.file:
        name: "{{ zsh_directory }}"
        state: absent

    - name: Remove config files
      ansible.builtin.file:
        name: "{{ item.dest_path }}/{{ item.file }}"
        state: absent
      loop: "{{ config_files }}"

    - name: Purge git and zsh packages
      ansible.builtin.package:
        name: zsh
        state: absent

    - name: Change the default shell to Bash
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/bash
  tags: purge::shell

- name: Setup shell
  hosts: all
  become: yes
  tasks:
    - name: Ensure git and zsh present
      ansible.builtin.package:
        name: 
          - git
          - zsh
        state: present

    - name: Ensure .zsh directory exists
      ansible.builtin.file:
        path: "{{ zsh_directory }}"
        state: directory

    - name: Clone zsh theme and plugins repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        depth: "{{ item.depth }}"
        update: no
      loop: "{{ zsh_repositories }}"

    - name: Ensure configuration files are copied
      ansible.builtin.copy:
        src: "config/{{ item.file }}"
        dest: "{{ item.dest_path }}/{{ item.file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "{{ item.mode }}"
      loop: "{{ config_files }}"

    - name: Change the default shell to Zsh
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
  tags: setup::shell