---

- name: Purge syncthing
  hosts: all
  become: yes
  pre_tasks:
    - name: Skip play if purge is disabled
      ansible.builtin.meta: end_play
      when: not purge_vars.syncthing
  tasks:
    - name: Delete syncthing package
      ansible.builtin.package:
        name: syncthing 
        state: absent
  tags: purge::syncthing

- name: Install syncthing
  hosts: all
  become: yes
  tasks:
    - name: Ensure syncthing is installed
      ansible.builtin.package:
        name: syncthing 
        state: present

    - name: Start syncthing
      ansible.builtin.shell: syncthing --no-browser &

    - name: Wait for syncthing to start
      ansible.builtin.wait_for:
        port: 8384
        delay: 10
        timeout: 30

    - name: Display syncthing Web GUI URL
      ansible.builtin.debug:
        msg: "SyncThing is running! Access the Web GUI at http://{{ inventory_hostname }}:8384"
  tags: install::syncthing
