---

- name: Purge syncthing
  hosts: all
  become: yes
  pre_tasks:
    - name: Skip play if purge is disabled
      ansible.builtin.meta: end_play
      when: purge_vars.syncthing is false
  tasks:
    - name: Delete syncthing package
      ansible.builtin.package:
        name: syncthing 
        state: absent
  tags: purge::syncthing

- name: Install syncthing
  hosts: all
  become: yes
  tasks:
    - name: Ensure syncthing is installed
      ansible.builtin.package:
        name: syncthing 
        state: present
  tags: install::syncthing
