---

extra_packages: []

extra_repositories:
  - name: "docker"
    repo_url: "https://download.docker.com/linux/ubuntu"
    gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    gpg_extention: "asc"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "stable"