---

all:
  children:
    workstations:
      hosts:
        ubuntu_thinkpad:
          ansible_host: "127.0.0.1"
          ansible_user: "{{ tp_ws_user }}"
          ansible_ssh_pass: "{{ tp_ws_pass }}"
          ansible_become_password: "{{ tp_ws_pass }}"
    servers:
      hosts:
        ubuntu_docker_node:
          ansible_host: "{{ lan_prefix }}.11"
          ansible_user: "{{ docker_node_user }}"
          ansible_ssh_pass: "{{ docker_node_pass }}"
          ansible_become_password: "{{ docker_node_pass }}"
    raspberries:
      hosts:
        raspberry_pi_1:
          ansible_host: "{{ lan_prefix }}.10"
          ansible_user: "{{ rbp_user }}"
          ansible_ssh_pass: "{{ rbp_pass }}"
          ansible_become_password: "{{ rbp_pass }}"
    proxmox:
      hosts:
        proxmox_optiplex:
          ansible_host: "{{ lan_prefix }}.30"
          ansible_user: "root"
          ansible_ssh_pass: "{{ proxmox_pass }}"
          ansible_become_password: "{{ proxmox_pass }}"
          # ansible_ssh_pass: "00000000"
          # ansible_become_password: "00000000"
    k8s:
      children:
        k8s_controlplanes:
          hosts:
            k8s-controlplane-01:
              ansible_host: "{{ lan_prefix }}.51"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
            k8s-controlplane-02:
              ansible_host: "{{ lan_prefix }}.52"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
            k8s-controlplane-03:
              ansible_host: "{{ lan_prefix }}.53"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
        k8s_workers:
          hosts:
            k8s-worker-01:
              ansible_host: "{{ lan_prefix }}.54"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
            k8s-worker-02:
              ansible_host: "{{ lan_prefix }}.55"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"