---

- name: Deploy Proxmox
  hosts: proxmox
  become: true
  handlers:
    - import_tasks: ../tasks/handlers/main.yml
  tasks:
    - name: Configure and deploy glance agent
      ansible.builtin.import_tasks: ../tasks/system/glance-agent.yml
      tags: proxmox::glance

    - name: Configure and deploy monitoring tools (node explorer for prometheus & promtail for loki)
      ansible.builtin.import_tasks: ../tasks/system/monitoring.yml
      tags: proxmox::monitoring
    