---

- name: Deploy server
  hosts: servers
  become: true
  handlers:
    - import_tasks: ../tasks/handlers/main.yml
  tasks:
    - name: Purge
      ansible.builtin.import_tasks: ../tasks/purge.yml
      when: purge_all
      tags: server::purge

    - name: Deploy
      block:     
        - name: Import packages tasks
          ansible.builtin.import_tasks: ../tasks/system/packages.yml
          vars:
            packages: "{{ common_packages + server_packages }}"
            deb_packages: "{{ common_deb_packages + server_deb_packages }}"
            python_packages: "{{ server_python_packages }}"
          tags: server::packages
        
        - name: Import repositories tasks
          ansible.builtin.import_tasks: ../tasks/system/repositories.yml
          vars:
            repositories: "{{ server_repositories }}"
          tags: server::repositories

        - name: Import filesystem tasks
          ansible.builtin.import_tasks: ../tasks/system/filesystem.yml
          vars:
            directories: "{{ common_directories + server_directories }}"
            disk_lvs: "{{ server_disk_lvs }}"
          tags: server::filesystem
        
        - name: Import shell tasks
          ansible.builtin.import_tasks: ../tasks/system/shell.yml
          tags: server::shell
        
        - name: Import rclone tasks
          ansible.builtin.import_tasks: ../tasks/system/rclone-clouds.yml
          vars:
            rclone_configs: "{{ common_rclone_configs + server_rclone_configs }}"
            rclone_mounts: "{{ common_rclone_mounts + server_rclone_mounts }}"
          tags: server::rclone

        - name: Import docker tasks
          ansible.builtin.import_tasks: ../tasks/docker/docker.yml
          vars:
            docker_networks: "{{ server_docker_networks }}"
            docker_plugins: "{{ server_docker_plugins }}"
          tags: server::docker
        
        - name: Import docker services tasks
          ansible.builtin.import_tasks: ../tasks/docker/services.yml
          vars:
            docker_services: "{{ server_docker_services }}"
            docker_services_configs: "{{ server_docker_services_configs }}"
            docker_services_crons: "{{ server_docker_services_crons }}"
          tags: server::docker::services
        
        - name: Import backup tasks
          ansible.builtin.import_tasks: ../tasks/system/restic-backups.yml
          vars:
            restic_backup_configs: "{{ server_restic_backup_configs }}"
          tags: server::backup

        - name: Import systemd services tasks
          ansible.builtin.import_tasks: ../tasks/system/services.yml
          vars:
            systemd_services: "{{ server_systemd_services }}"
          tags: server::services
