---

- name: Install docker packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ docker_packages }}"

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Create docker group if not exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create required networks
  community.docker.docker_network:
    name: "{{ item }}"
  loop: "{{ docker_networks }}"