---

- name: Create services directories
  block:
    - name: Create data directory for each service
      ansible.builtin.file:
        path: "{{ docker_services_directory }}/{{ item.0.stack_name }}/data/{{ item.1 }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
        mode: '0755'
      loop: "{{ docker_services | subelements('services') }}"
      loop_control:
        label: "{{ docker_services_directory }}/{{ item.0.stack_name }}/data/{{ item.1 }}"
    
    - name: Create config directory for each service
      ansible.builtin.file:
        path: "{{ docker_services_directory }}/{{ item.0.stack_name }}/config/{{ item.1 }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
        mode: '0755'
      loop: "{{ docker_services | subelements('services') }}"
      loop_control:
        label: "{{ docker_services_directory }}/{{ item.0.stack_name }}/config/{{ item.1 }}"

- name: Template docker-compose file for the services
  ansible.builtin.template:
    src: "templates/docker/{{ item.stack_name }}/docker-compose.yml.j2"
    dest: "{{ docker_services_directory }}/{{ item.stack_name }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ docker_services }}"
  loop_control:
    label: "{{ docker_services_directory }}/{{ item.stack_name }}/docker-compose.yml"

- name: Template config files for the services
  ansible.builtin.template:
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ docker_services | subelements('configs') }}"
  loop_control:
    label: "{{ item.1.dest }}"

- name: Run docker-compose services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_services_directory }}/{{ item.stack_name }}"
    remove_orphans: yes
  loop: "{{ docker_services }}"
  loop_control:
    label: "{{ item.stack_name }}"

- name: Add services cron jobs
  ansible.builtin.cron:
    name: "{{ item.1.name }}"
    job: "docker exec -u {{ item.1.service_user }} {{ item.1.service }} {{ item.1.job }}"
    month: "{{ item.1.month | default('*')}}"
    weekday: "{{ item.1.weekday | default('*') }}"
    day: "{{ item.1.day | default('*') }}"
    hour: "{{ item.1.hour | default('*') }}"
    minute: "{{ item.1.minute | default('*') }}"
    user: "{{ ansible_user }}"
  loop: "{{ docker_services | subelements('crons') }}"
  loop_control:
    label: "{{ item.1.name }}"
