---

- name: Create services directories
  block:
    - name: Create main directory
      ansible.builtin.file:
        name: "{{ docker_services_directory }}/{{ item.name }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
      loop: "{{ docker_services }}"

    - name: Create data directory
      ansible.builtin.file:
        name: "{{ docker_services_directory }}/{{ item.name }}/data"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
      loop: "{{ docker_services }}"
    
    - name: Create config directory
      ansible.builtin.file:
        name: "{{ docker_services_directory }}/{{ item.name }}/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
      loop: "{{ docker_services }}"

- name: Template docker-compose file for the services
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_services_directory }}/{{ stack.name }}/docker-compose.yml"
  loop: "{{ docker_services }}"
  loop_control:
    loop_var: stack

- name: Template config files for the services
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ docker_services_configs }}"

- name: Run docker-compose services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_services_directory }}/{{ item.name }}"
    state: present
  loop: "{{ docker_services }}"