---

- name: Create services directories
  ansible.builtin.file:
    name: "{{ docker_services_directory }}/{{ item.name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  loop: "{{ docker_services }}"

- name: Template docker-compose file for the services
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_services_directory }}/{{ stack.name }}/docker-compose.yml"
  loop: "{{ docker_services }}"
  loop_control:
    loop_var: stack

- name: Run postgres database docker-compose service
  community.docker.docker_compose_v2:
    project_src: "{{ docker_services_directory }}/postgres"
    state: present

- name: Create postgres databases
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    state: present
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgresdb_user }}"
    login_password: "{{ postgresdb_password }}"
  loop: "{{ databases }}"

- name: Create postgres users
  community.postgresql.postgresql_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    state: present
    login_host: "{{ postgres_host }}"
    login_db: "{{ postgresdb }}"
    login_user: "{{ postgresdb_user }}"
    login_password: "{{ postgresdb_password }}"
  loop: "{{ databases }}"

- name: Grant privileges to users on their databases
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    roles: "{{ item.user }}"
    type: database
    privs: ALL
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgresdb_user }}"
    login_password: "{{ postgresdb_password }}"
  loop: "{{ databases }}"

- name: Run docker-compose services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_services_directory }}/{{ item.name }}"
    state: present
  loop: "{{ docker_services }}"