---

- name: Create filesystem on disk
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "{{ item.device }}"
  loop: "{{ disks_fs | default([]) }}"
  when: item.fstype != "virtiofs"

- name: Mount volumes
  ansible.posix.mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop: "{{ disks_fs | default([]) }}"

- name: Create directories
  ansible.builtin.file:
    name: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  loop: "{{ directories | default([]) }}"