---

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - unzip
      - tar
    state: present

- name: Install & config Promtail
  block:
    - name: Install Promtail
      ansible.builtin.apt:
        deb: "{{ promtail_package_url }}"

    - name: Template config file
      ansible.builtin.template:
        src: "common/promtail/promtail-config.yml.j2"
        dest: "/etc/promtail/config.yml"
    
    - name: Restart promtail service
      ansible.builtin.systemd:
        name: promtail
        state: restarted
        daemon_reload: true

- name: Install & config Node Exporter
  block:
    - name: Download and extract node_exporter binary
      ansible.builtin.unarchive:
        src: "{{ node_exporter_archive_url }}"
        dest: /usr/local/bin/
        remote_src: true
        mode: '0755'
        extra_opts:
          - --strip-components=1
        creates: /usr/local/bin/node_exporter
    
    - name: Configure and start node_exporter systemd service
      ansible.builtin.import_tasks: services.yml
      vars:
        systemd_services: "{{ node_exporter_systemd_service }}"