---

- name: Install system packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages | default([]) }}"

- name: Install deb packages from url
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ deb_packages | default([]) }}"

- name: Install python packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ python_packages | default([]) }}"