---

- name: Ensure restic is installed
  ansible.builtin.package:
    name: restic
    state: present

- name: Ensure local backup directories exists
  ansible.builtin.file:
    path: "{{ item.local_backup_repo }}"
    state: directory
    mode: '0755'
  loop: "{{ restic_backup_configs | default([]) }}"

- name: Initialize Restic local Repository
  environment: "{{ restic_env_vars }}"
  ansible.builtin.command: 
    cmd: restic init --repo {{ item.local_backup_repo }}
    creates: "{{ item.local_backup_repo }}/config"
  loop: "{{ restic_backup_configs | default([]) }}"

- name: Restic remote Repository
  block:
    # - name: Verify restic remote
    #   ansible.builtin.command: "{{ restic_remote_verify_command }}"
    #   register: verify_result
    #   ignore_errors: true

    # - name: Assert that restic remote is accessible
    #   ansible.builtin.assert:
    #     that:
    #       - verify_result.rc == 0
    #     fail_msg: "Restic remote verification failed for {{ restic_remote }}"
    #     success_msg: "Restic remote for {{ restic_remote }} is accessible"

    - name: Check if restic remote repo is initialized
      ansible.builtin.command: "restic snapshots --repo {{ item.remote_backup_repo }}"
      environment: "{{ restic_env_vars }}"
      register: restic_check
      ignore_errors: true
      loop: "{{ restic_backup_configs | default([]) }}"
      loop_control:
        label: "{{ item.name }}"
    
    - name: Initialize restic remote repo if it is not initialized
      ansible.builtin.command: "restic init --repo {{ item.remote_backup_repo }}"
      environment: "{{ restic_env_vars }}"
      when: restic_check.results[idx].rc != 0
      loop: "{{ restic_backup_configs | default([]) }}"
      loop_control:
        index_var: idx
        label: "{{ item.name }}"

- name: Ensure restic directories are created
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
  loop:
    - "{{ restic_scripts_directory }}"
    - "{{ restic_logs_directory }}"

- name: Template restic backup scripts
  ansible.builtin.template:
    src: common/restic/backup.sh.j2
    dest: "{{ restic_scripts_directory }}/{{ restic_backup_config.name }}-backup.sh"
    owner: root
    group: root
    mode: '0700'
  loop: "{{ restic_backup_configs | default([]) }}"
  loop_control:
    loop_var: restic_backup_config

- name: Ensure a cron job for Restic backup
  ansible.builtin.cron:
    name: "Restic backup for {{ item.name }}"
    job: "{{ restic_scripts_directory }}/{{ item.name }}-backup.sh"
    month: "{{ item.cron.month | default('*')}}"
    weekday: "{{ item.cron.weekday | default('*') }}"
    day: "{{ item.cron.day | default('*') }}"
    hour: "{{ item.cron.hour | default('*') }}"
    minute: "{{ item.cron.minute | default('*') }}"
    user: root
  loop: "{{ restic_backup_configs | default([]) }}"
