---

- name: Ensure zsh packages present
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ zsh_packages }}"

- name: Ensure .zsh directory exists
  ansible.builtin.file:
    path: "{{ zsh_directory }}"
    state: directory

- name: Clone zsh theme and plugins repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: "{{ item.depth }}"
    update: false
  loop: "{{ zsh_repositories }}"

- name: Ensure configuration files are copied
  ansible.builtin.copy:
    src: "files/common/shell/config/{{ item.file }}"
    dest: "{{ item.dest_path }}/{{ item.file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ item.mode }}"
  loop: "{{ config_files }}"

- name: Change the default shell to Zsh
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
