---

backup_mount: "/mnt/backup"

media_mount: "/mnt/media"

docker_traefik_subnet: '172.18.0.0/16'

loki_url: "http://loki:3100"

promtail_instance: "svr"

server_deb_packages: []

server_directories:
  - "{{ backup_mount }}/docker_backup"
  - "{{ media_mount }}/library/books"
  - "{{ media_mount }}/library/courses"
  - "{{ media_mount }}/library/movies"
  - "{{ media_mount }}/library/music"
  - "{{ media_mount }}/library/other"
  - "{{ media_mount }}/library/quran"
  - "{{ media_mount }}/library/tv"
  - "{{ media_mount }}/torrents"

server_disk_lvs:
  - lv: "lv_backup" # 256G
    vg: "vg_sata"
    mount_point: "{{ backup_mount }}"
    fstype: "ext4"
  - lv: "lv_media" # 512G
    vg: "vg_sata"
    mount_point: "{{ media_mount }}"
    fstype: "xfs"

server_docker_networks:
  - frontend
  - backend

server_docker_plugins:
  - name: "grafana/loki-docker-driver:3.4.3-amd64"
    alias: "loki"

server_docker_services:
  - stack_name: "home"
    services:
      - "home-assistant"
    templates:
      - src: "templates/docker/home/config/home-assistant/configuration.yaml.j2"
        dest: "{{ docker_services_directory }}/home/config/home-assistant/configuration.yaml"
      - src: "templates/docker/home/config/home-assistant/packages/plugs.yaml.j2"
        dest: "{{ docker_services_directory }}/home/config/home-assistant/packages/plugs.yaml"
    configs: []
    crons: []
  - stack_name: "toolbox"
    services:
      - "authelia"
      - "traefik"
      - "whoami"
      - "cloudflare-ddns"
      - "portainer"
      - "postgres"
      - "gluetunvpn"
      - "qbittorrent"
      - "vaultwarden"
    templates:
      - src: "templates/docker/toolbox/config/traefik/external-services.yml.j2"
        dest: "{{ docker_services_directory }}/toolbox/config/traefik/external-services.yml"
      - src: "templates/docker/toolbox/config/traefik/traefik.yml.j2"
        dest: "{{ docker_services_directory }}/toolbox/config/traefik/traefik.yml"
      - src: "templates/docker/toolbox/config/authelia/users_database.yml.j2"
        dest: "{{ docker_services_directory }}/toolbox/config/authelia/users_database.yml"
      - src: "templates/docker/toolbox/config/authelia/configuration.yml.j2"
        dest: "{{ docker_services_directory }}/toolbox/config/authelia/configuration.yml"
    configs: []
    crons: []
  - stack_name: "monitoring"
    services:
      - "grafana"
      - "prometheus"
      - "loki"
      - "cadvisor"
      - "node_exporter"
      - "promtail"
    templates:
      - src: "templates/docker/monitoring/config/prometheus/prometheus.yml.j2"
        dest: "{{ docker_services_directory }}/monitoring/config/prometheus/prometheus.yml"
      - src: "templates/docker/monitoring/config/loki/loki-config.yml.j2"
        dest: "{{ docker_services_directory }}/monitoring/config/loki/loki-config.yml"
      - src: "templates/docker/monitoring/config/promtail/promtail-config.yml.j2"
        dest: "{{ docker_services_directory }}/monitoring/config/promtail/promtail-config.yml"
    configs: []
    crons: []
  - stack_name: "media"
    services:
      - "jellyfin"
      - "jellyseerr"
      - "prowlarr"
      - "flaresolverr"
      - "radarr"
      - "sonarr"
      - "bazarr"
    templates: []
    configs: []
    crons: []
  - stack_name: "nextcloud"
    services:
      - "nextcloud-app"
      - "nextcloud-redis"
      - "nextcloud-db"
      - "nextcloud-onlyoffice"
    templates:
      - src: "templates/docker/nextcloud/config/nextcloud-app/nextcloud.ini.j2"
        dest: "{{ docker_services_directory }}/nextcloud/config/nextcloud-app/nextcloud.ini"
    configs: []
    crons:
      - name: "Nextcloud cron job"
        service: "nextcloud-app"
        service_user: "www-data"
        job: "php /var/www/html/cron.php"
        minute: "*/5"

server_packages:
  - lvm2
  - parted
  - python3-psycopg2

server_python_packages: []

server_rclone_configs:
  # - name: "backblaze"
  #   properties:
  #     type: "b2"
  #     account: "{{ b2_account }}"
  #     key: "{{ b2_appkey }}"
  # - name: "mega"
  #   properties:
  #     type: "mega"
  #     user: "{{ mega_username }}"
  #     pass: "{{ mega_encpassword }}"
  - name: "protondrive"
    properties:
      type: "protondrive"
      username: "{{ proton_username }}"
      password: "{{ proton_encpassword }}"
      2fa: "{{ proton_2fa }}"
      replace_existing_draft: "true"
      enable_caching: "false"

server_rclone_mounts:
  # - name: "backblaze"
  #   remote_name: "backblaze" 
  #   remote_path: "/"
  #   local_path: "/mnt/backblaze"
  #   local_path_mode: "0755"
  #   local_path_owner: "{{ rclone_config_owner.OWNER }}"
  #   local_path_group: "{{ rclone_config_owner.GROUP }}"
  #   auto_mount: true
  #   extra_args: "--allow-other"
  # - name: "mega"
  #   remote_name: "mega" 
  #   remote_path: "/"
  #   local_path: "/mnt/mega"
  #   local_path_mode: '0755'
  #   local_path_owner: "{{ rclone_config_owner.OWNER }}"
  #   local_path_group: "{{ rclone_config_owner.GROUP }}"
  #   auto_mount: true
  #   extra_args: "--allow-other"
  - name: "protondrive"
    remote_name: "protondrive" 
    remote_path: "/"
    local_path: "/mnt/protondrive"
    local_path_mode: '0755'
    local_path_owner: "{{ rclone_config_owner.OWNER }}"
    local_path_group: "{{ rclone_config_owner.GROUP }}"
    auto_mount: true
    extra_args: "--allow-other"

server_repositories:
  - name: "docker"
    repo_url: "https://download.docker.com/linux/debian"
    gpg_url: "https://download.docker.com/linux/debian/gpg"
    gpg_extention: "asc"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "stable"

server_restic_backup_configs:
  - name: "docker-services"
    dir_to_backup: "/opt/docker_services"
    local_backup_repo: "{{ backup_mount }}/docker_backup"
    remote_backup_repo: "{{ restic_remote }}:docker_backup"
    cron:
      hour: "4"
      minute: "0"

server_systemd_services: []

template_docker_daemon: yes