---

workstation_deb_packages: []

workstation_docker_networks: []

workstation_docker_plugins: []

workstation_docker_services: []

workstation_docker_services_configs: []

workstation_docker_services_crons: []

workstation_directories: []

workstation_packages: 
  - brave-browser
  - code
  - openjdk-17-jdk
  - python3-psycopg2

workstation_python_packages: []

workstation_rclone_configs: []

workstation_rclone_mounts: []

workstation_repositories:
  - name: "docker"
    repo_url: "https://download.docker.com/linux/ubuntu"
    gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    gpg_extention: "asc"
    components:
      - "{{ ansible_facts['distribution_release'] }}"
      - "stable"

workstation_systemd_services: []
