---

authelia_domains_policy:
  - domain: "*.{{ domain_name }}"
    policy: "one_factor"
authelia_oidc_clients:
  - id: "grafana"
    properties:
      client_name: "Grafana"
      client_secret: "{{ authelia_oidc_clients_secrets.grafana.secret_hash }}"
      public: false
      authorization_policy: "two_factor"
      require_pkce: true
      pkce_challenge_method: "S256"
      redirect_uris:
        - "https://grafana.{{ domain_name }}/login/generic_oauth"
      scopes:
        - "openid"
        - "profile"
        - "groups"
        - "email"
      userinfo_signing_algorithm: "none"
      token_endpoint_auth_method: "client_secret_basic"
  - id: "homarr"
    properties:
      client_name: "Homarr"
      secret: "{{ authelia_oidc_clients_secrets.homarr.secret_hash }}"
      public: false
      authorization_policy: "two_factor"
      redirect_uris:
        - "https://homarr.{{ domain_name }}/api/auth/callback/oidc"
      scopes:
        - "openid"
        - "profile"
        - "groups"
        - "email"
      userinfo_signing_algorithm: "none"
      token_endpoint_auth_method: "client_secret_basic"
  - id: "nextcloud"
    properties:
      description: "Nextcloud"
      secret: "{{ authelia_oidc_clients_secrets.nextcloud.secret_hash }}"
      public: false
      authorization_policy: "two_factor"
      require_pkce: true
      pkce_challenge_method: "S256"
      redirect_uris:
        - "https://cloud.{{ domain_name }}/apps/oidc_login/oidc"
      scopes:
        - "openid"
        - "profile"
        - "groups"
        - "email"
      userinfo_signing_algorithm: "none"
      token_endpoint_auth_method: "client_secret_basic"
  - id: "portainer"
    properties:
      description: "Portainer"
      secret: "{{ authelia_oidc_clients_secrets.portainer.secret_hash }}"
      public: false
      authorization_policy: "two_factor"
      redirect_uris:
        - "https://portainer.{{ domain_name }}"
      scopes:
        - "openid"
        - "profile"
        - "groups"
        - "email"
      userinfo_signing_algorithm: "none"
      token_endpoint_auth_method: 'client_secret_post'

docker_traefik_subnet: '172.18.0.0/16'

glance_monitor_services:
  - title: "Network & Infra"
    sites:
      - name: "Pihole"
        url: "https://pihole.{{ domain_name }}/admin"
      - name: "Gateway"
        url: "https://gateway.{{ domain_name }}"
        icon: "si:eclipsemosquitto"
      - name: "Proxmox"
        url: "https://proxmox.{{ domain_name }}"
      - name: "Traefik"
        url: "https://proxy.{{ domain_name }}"
        icon: "si:traefikproxy"
      - name: "Authelia"
        url: "https://sso.{{ domain_name }}"
      - name: "Speedtest"
        url: "https://speedtest.{{ domain_name }}"
      - name: "Grafana"
        url: "https://grafana.{{ domain_name }}"
      - name: "Portainer"
        url: "https://portainer.{{ domain_name }}"
  - title: "Services"
    sites:
      - name: "Nextcloud"
        url: "https://cloud.{{ domain_name }}"
      - name: "Paperless"
        url: "https://paperless.{{ domain_name }}"
        icon: "si:paperlessngx"
      - name: "Vaultwarden"
        url: "https://vaultwarden.{{ domain_name }}"
      - name: "Home assistant"
        url: "https://home-assistant.{{ domain_name }}"
      - name: "N8n"
        url: "https://n8n.{{ domain_name }}"
  - title: "Media"
    sites:
      - name: "Jellyfin"
        url: "https://jellyfin.{{ domain_name }}"
      - name: "Jellyseerr"
        url: "https://jellyseerr.media.{{ domain_name }}"
        icon: "sh:jellyseerr"
      - name: "Radarr"
        url: "https://radarr.media.{{ domain_name }}"
      - name: "Sonarr"
        url: "https://sonarr.media.{{ domain_name }}"
      - name: "Bazarr"
        url: "https://bazarr.media.{{ domain_name }}"
        icon: "sh:bazarr"
      - name: "Dispatcharr"
        url: "https://iptv.{{ domain_name }}"
        icon: "sh:dispatcharr"
      - name: "Prowlarr"
        url: "https://prowlarr.media.{{ domain_name }}"
        icon: "sh:prowlarr"
      - name: "Qbittorrent"
        url: "https://torrent.{{ domain_name }}"

glance_mountpoints_to_monitor:
  - name: "Root"
    path: "/"
  - name: "Docker services"
    path: "{{ docker_services_directory }}"
  - name: "Backup"
    path: "{{ backup_mount }}"
  - name: "Media"
    path: "{{ media_mount }}"
  # - name: "Proxmox backup"
  #   path: ""

home_assistant_zigbee_dongle: "usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_b09546f368f3ef11a606c21b6d9880ab-if00-port0"

loki_url: "http://loki:3100"

promtail_instance: "svr"
