---

- name: Add k8s repository
  ansible.builtin.import_tasks: ../common/repositories.yml

- name: Install required packages
  ansible.builtin.import_tasks: ../common/packages.yml

- name: Hold k8s packages at current version
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ k8s_packages }}"

- name: Ensure containerd conf directory exists
  ansible.builtin.file:
    name: "/etc/containerd"
    state: directory

- name: Template containerd config 
  ansible.builtin.template:
    src: "../templates/k8s/containerd/config.toml.j2"
    dest: "/etc/containerd/config.toml"

- name: Config crictl
  ansible.builtin.copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
      debug: false

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: yes
  