---

- name: Enable and start iscsid service
  ansible.builtin.systemd:
    name: iscsid
    enabled: true
    state: started

- name: Format longhorn disk
  ansible.builtin.filesystem:
    fstype: "ext4"
    dev: "/dev/sdb"

- name: Mount longhorn disk
  ansible.posix.mount:
    path: "/mnt/longhorn"
    src: "/dev/sdb"
    fstype: "ext4"
    state: mounted

- name: Disable and stop multipathd socket and service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - multipathd.socket
    - multipathd
