---

- name: Extract cilium-cli
  ansible.builtin.unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes

- name: Check if Cilium is already installed
  ansible.builtin.command: cilium status
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: cilium_status
  failed_when: false
  changed_when: false

- name: Install Cilium
  ansible.builtin.command: >
    cilium install
    --version {{ cilium_version }}
    --set kubeProxyReplacement=true
    --set k8sServiceHost={{ k8s_vip }}
    --set k8sServicePort=6443
  environment:
    CILIUM_CLI_SKIP_REACHABILITY_CHECK: 1
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: cilium_status.rc != 0

- name: Wait for Cilium to be ready
  ansible.builtin.command: cilium status --wait
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  retries: 5
  delay: 15
  when: cilium_status.rc != 0