---

- hosts: jenkins-master
  tasks:
    - name: Install Jenkins plugins
      become: yes
      command: >
        "java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 install-plugin {{ item }}"
      environment:
        JENKINS_HOME: /var/jenkins_home
      loop:
        - docker
        - plugin2
        # Add more plugins as needed

- hosts: jenkins-slaves
  tasks:
    - name: Register Jenkins slave
      become: yes
      command: >
        java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 create-node SLAVE_NAME
      environment:
        JENKINS_HOME: /var/jenkins_home
      vars:
        SLAVE_NAME: "{{ inventory_hostname }}"
