---

all:
  hosts:
    docker_node:
      ansible_host: "{{ lan_prefix }}.21"
      ansible_user: "{{ docker_node_user }}"
      ansible_ssh_pass: "{{ docker_node_pass }}"
      ansible_become_password: "{{ docker_node_pass }}"
    ubuntu_lxc:
      ansible_host: "{{ lan_prefix }}.81"
      ansible_user: "root"
      ansible_ssh_pass: "{{ ubuntu_lxc_pass }}"
      ansible_become_password: "{{ ubuntu_lxc_pass }}"
  children:
    workstations:
      hosts:
        thinkpad:
          ansible_host: "127.0.0.1"
          ansible_user: "{{ tp_ws_user }}"
          ansible_ssh_pass: "{{ tp_ws_pass }}"
          ansible_become_password: "{{ tp_ws_pass }}"
    network:
      hosts:
        raspberry:
          ansible_host: "{{ lan_prefix }}.10"
          ansible_user: "{{ rbp_user }}"
          ansible_ssh_pass: "{{ rbp_pass }}"
          ansible_become_password: "{{ rbp_pass }}"
    proxmox:
      hosts:
        pve:
          ansible_host: "{{ lan_prefix }}.100"
          ansible_user: "root"
          ansible_ssh_pass: "{{ pve_pass }}"
          ansible_become_password: "{{ pve_pass }}"
    k8s:
      children:
        k8s_controlplanes:
          hosts:
            k8s-controlplane-01:
              ansible_host: "{{ lan_prefix }}.31"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
            k8s-controlplane-02:
              ansible_host: "{{ lan_prefix }}.32"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
            k8s-controlplane-03:
              ansible_host: "{{ lan_prefix }}.33"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
        k8s_workers:
          hosts:
            k8s-worker-01:
              ansible_host: "{{ lan_prefix }}.34"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
            k8s-worker-02:
              ansible_host: "{{ lan_prefix }}.35"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"
            k8s-worker-03:
              ansible_host: "{{ lan_prefix }}.36"
              ansible_user: "{{ k8s_user }}"
              ansible_ssh_pass: "{{ k8s_pass }}"
              ansible_become_password: "{{ k8s_pass }}"