---

all:
  children:
    workstations:
      hosts:
        ubuntu_thinkpad:
          ansible_host: "127.0.0.1"
          ansible_user: "{{ tp_ws_user }}"
          ansible_ssh_pass: "{{ tp_ws_pass }}"
          ansible_become_password: "{{ tp_ws_pass }}"
    servers:
      hosts:
        debian_thinkcenter:
          ansible_host: "{{ lan_prefix }}.20"
          ansible_user: "{{ tc_svr_user }}"
          ansible_ssh_pass: "{{ tc_svr_pass }}"
          ansible_become_password: "{{ tc_svr_pass }}"
    raspberries:
      hosts:
        raspberry_pi_1:
          ansible_host: "{{ lan_prefix }}.10"
          ansible_user: "{{ rbp_user }}"
          ansible_ssh_pass: "{{ rbp_pass }}"
          ansible_become_password: "{{ rbp_pass }}"