---

- name: Add GPG keys and repositories
  hosts: all
  become: true
  tasks:
    - name: Ensure the keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add GPG keys
      ansible.builtin.get_url:
        url: "{{ item.gpg_url }}"
        dest: "{{ item.gpg_keyring }}"
        mode: '0644'
      loop: "{{ repositories }}"
      notify: update_apt_cache

    - name: Add repositories
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        filename: "{{ item.repo_list_file | basename }}"
        state: present
      loop: "{{ repositories }}"
      notify: update_apt_cache

  handlers:
    - name: update_apt_cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600