---

- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages_to_install }}"