---

- name: "Add repositories"
  ansible.builtin.import_playbook: add_repositories.yml
  tags: common::repositories

- name: "Install packages"
  ansible.builtin.import_playbook: install_packages.yml
  tags: common::packages

- name: "Setup shell"
  ansible.builtin.import_playbook: setup_shell.yml
  tags: common::shell

- name: "Setup docker"
  ansible.builtin.import_playbook: setup_docker.yml
  tags: common::docker