---

- name: Add GPG keys and repositories
  hosts: all
  become: yes
  tasks:
    - name: Purge GPG keys and repositories
      block:
        - name: Remove GPG keys
          ansible.builtin.file:
            name: "/etc/apt/trusted.gpg.d/{{ item.name }}.asc"
            state: absent
          loop: "{{ repositories }}"

        - name: Remove repositories sources list files
          ansible.builtin.file:
            name: "/etc/apt/sources.list.d/{{ item.name }}-archive"
            state: absent
          loop: "{{ repositories }}"
          notify: update_apt_cache
      when: purge_vars.repositories
      tags: purge::repositories

    - name:
      block:
        - name: Add GPG keys
          ansible.builtin.get_url:
            url: "{{ item.gpg_url }}"
            dest: "/etc/apt/trusted.gpg.d/{{ item.name }}.asc"
          loop: "{{ repositories }}"

        - name: Add APT repositories
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/trusted.gpg.d/{{ item.name }}.asc] {{ item.repo_url }} {{ ansible_lsb.codename }} {{ item.components | join(' ') }}"
            filename: "{{ item.name }}-archive"
            state: present
          loop: "{{ repositories }}"
          notify: update_apt_cache
      tags: add::repositories

  handlers:
    - name: update_apt_cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600