---

- name: Purge packages
  hosts: all
  become: yes
  pre_tasks:
    - name: Skip play if purge is disabled
      ansible.builtin.meta: end_play
      when: purge_vars.packages is false
  tasks:
    - name: Purge packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"
  tags: purge::packages

- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
  tags: Install::packages