---

- name: Test Bitwarden Lookup
  hosts: localhost
  vars:
    test_username: "{{ lookup('community.general.bitwarden', 'd8478663-814a-4afe-8e68-b1e00153ab4c', field='login[username]') }}"
    test_password: "{{ lookup('community.general.bitwarden', 'd8478663-814a-4afe-8e68-b1e00153ab4c', field='login[password]') }}"
  tasks:
    - name: Display fetched username
      debug:
        msg: "Fetched username: {{ test_username }}"
    - name: Display fetched password
      debug:
        msg: "Fetched password: {{ test_password | default('not set') }}"