---

- name: "Workstation deploy"
  ansible.builtin.import_playbook: workstation-deploy.yml

- name: "Server deploy"
  ansible.builtin.import_playbook: server-deploy.yml

- name: "Raspberry PI deploy"
  ansible.builtin.import_playbook: raspberry-deploy.yml
