---

- name: Deploy raspberry
  hosts: raspberries
  become: yes
  tasks:
    - name: Import packages tasks
      ansible.builtin.import_tasks: tasks/system/packages.yml
      vars:
        packages: "{{ raspberry_packages }}"
        python_packages: []
      tags: raspberry::packages

    - name: Configure and deploy PiHole
      block:
      tags: raspberry::pihole

    - name: Configure and deploy PiVPN
      block:
      tags: raspberry::pivpn