---

- name: Deploy server
  hosts: servers
  become: yes
  vars:
    directories: "{{ common_directories + server_directories }}"
    directories_to_remove: "{{ common_directories_to_remove + server_directories_to_remove }}"
    packages: "{{ common_packages + server_packages }}"
    packages_to_purge: "{{ server_packages }}"
    python_packages: "{{ common_python_packages + workstation_python_packages }}"
    repositories: "{{ common_repositories + server_repositories }}"
    systemd_services: "{{ common_systemd_services + server_systemd_services }}"
    docker_networks: "{{ common_docker_networks + workstation_docker_networks }}"
    docker_services: "{{ common_docker_services + server_docker_services }}"
  tasks:
    - name: Purge
      ansible.builtin.import_tasks: tasks/purge.yml
      when: purge_all
      tags: server::purge

    - name: Deploy
      block:
        - name: Import directories tasks
          ansible.builtin.import_tasks: tasks/system/directories.yml
          tags: server::directories
        
        - name: Import repositories tasks
          ansible.builtin.import_tasks: tasks/system/repositories.yml
          tags: server::repositories
        
        - name: Import packages tasks
          ansible.builtin.import_tasks: tasks/system/packages.yml
          tags: server::packages
        
        - name: Import shell tasks
          ansible.builtin.import_tasks: tasks/system/shell.yml
          tags: server::shell
        
        - name: Import docker tasks
          ansible.builtin.import_tasks: tasks/docker/docker.yml
          tags: server::docker
        
        - name: Import docker services tasks
          ansible.builtin.import_tasks: tasks/docker/services.yml
          vars:
            postgresdb: "{{ lookup('community.general.bitwarden', 'postgres_service', field='database') | first }}"
            postgresdb_user: "{{ lookup('community.general.bitwarden', 'postgres_service', field='dbuser') | first }}"
            postgresdb_password: "{{ lookup('community.general.bitwarden', 'postgres_service', field='dbpassword') | first }}"
            nextclouddb: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='database') | first }}"
            nextclouddb_user: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='dbuser') | first }}"
            nextclouddb_password: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='dbpassword') | first }}"
            immichdb: "{{ lookup('community.general.bitwarden', 'immich_service', field='database') | first }}"
            immichdb_user: "{{ lookup('community.general.bitwarden', 'immich_service', field='dbuser') | first }}"
            immichdb_password: "{{ lookup('community.general.bitwarden', 'immich_service', field='dbpassword') | first }}"
            databases: "{{ server_databases }}"
          tags: server::docker::services
        
        - name: Import systemd services tasks
          ansible.builtin.import_tasks: tasks/system/services.yml
          tags: server::services
