---

- name: Deploy server
  hosts: servers
  become: yes
  pre_tasks:
    - name: Get secrets
      ansible.builtin.set_fact:
        postgres_db: "{{ lookup('community.general.bitwarden', 'postgres_service', field='database') | first }}"
        postgres_db_user: "{{ lookup('community.general.bitwarden', 'postgres_service', field='dbuser') | first }}"
        postgres_db_password: "{{ lookup('community.general.bitwarden', 'postgres_service', field='dbpassword') | first }}"
        nextcloud_db: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='database') | first }}"
        nextcloud_db_user: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='dbuser') | first }}"
        nextcloud_db_password: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='dbpassword') | first }}"
        nextcloud_root_db_password: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='rootdb_password') | first }}"
        nextcloud_onlyoffice_jwt: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='onlyoffice_jwt') | first }}"
        traefik_dns_api_token: "{{ lookup('community.general.bitwarden', 'traefik_service', field='cloudflare_token') | first }}"
        traefik_acme_email: "{{ lookup('community.general.bitwarden', 'traefik_service', field='acme_email') | first }}"
        traefik_domain_name: "{{ lookup('community.general.bitwarden', 'traefik_service', field='domain') | first }}"
        traefik_user: "{{ lookup('community.general.bitwarden', 'traefik_service', field='username') | first }}"
        traefik_hash_password: "{{ lookup('community.general.bitwarden', 'traefik_service', field='hash_password') | first }}"
        homarr_sec: "{{ lookup('community.general.bitwarden', 'homarr_service', field='sec') | first }}"
      tags: server::secrets
  tasks:
    - name: Purge
      ansible.builtin.import_tasks: tasks/purge.yml
      when: purge_all
      tags: server::purge

    - name: Deploy
      block:     
        - name: Import repositories tasks
          ansible.builtin.import_tasks: tasks/system/repositories.yml
          vars:
            repositories: "{{ server_repositories }}"
          tags: server::repositories
        
        - name: Import packages tasks
          ansible.builtin.import_tasks: tasks/system/packages.yml
          vars:
            packages: "{{ common_packages + server_packages }}"
            python_packages: "{{ server_python_packages }}"
          tags: server::packages

        - name: Import filesystem tasks
          ansible.builtin.import_tasks: tasks/system/filesystem.yml
          vars:
            directories: "{{ common_directories + server_directories }}"
            disk_partitions: "{{ server_disk_partitions }}"
            disk_vgs: "{{ server_disk_vgs }}"
            disk_lvs: "{{ server_disk_lvs }}"
          tags: server::filesystem
        
        - name: Import shell tasks
          ansible.builtin.import_tasks: tasks/system/shell.yml
          tags: server::shell
        
        - name: Import docker tasks
          ansible.builtin.import_tasks: tasks/docker/docker.yml
          vars:
            docker_networks: "{{ server_docker_networks }}"
          tags: server::docker
        
        - name: Import docker services tasks
          ansible.builtin.import_tasks: tasks/docker/services.yml
          vars:
            docker_services: "{{ server_docker_services }}"
            docker_services_configs: "{{ server_docker_services_configs }}"
            docker_services_crons: "{{ server_docker_services_crons }}"
          tags: server::docker::services
        
        - name: Import systemd services tasks
          ansible.builtin.import_tasks: tasks/system/services.yml
          vars:
            systemd_services: "{{ server_systemd_services }}"
          tags: server::services
