---

- name: Deploy server
  hosts: servers
  become: yes
  pre_tasks:
    - name: Get secrets
      ansible.builtin.set_fact:
        postgres_db: "{{ lookup('community.general.bitwarden', 'postgres_service', field='database') | first }}"
        postgres_db_user: "{{ lookup('community.general.bitwarden', 'postgres_service', field='dbuser') | first }}"
        postgres_db_password: "{{ lookup('community.general.bitwarden', 'postgres_service', field='dbpassword') | first }}"
        nextcloud_db: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='database') | first }}"
        nextcloud_db_user: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='dbuser') | first }}"
        nextcloud_db_password: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='dbpassword') | first }}"
        nextcloud_root_db_password: "{{ lookup('community.general.bitwarden', 'nextcloud_service', field='rootdb_password') | first }}"
        traefik_dns_api_token: "{{ lookup('community.general.bitwarden', 'traefik_service', field='cloudflare_token') | first }}"
        traefik_acme_email: "{{ lookup('community.general.bitwarden', 'traefik_service', field='acme_email') | first }}"
        traefik_domain_name: "{{ lookup('community.general.bitwarden', 'traefik_service', field='domain') | first }}"
        seafile_admin_email: "{{ lookup('community.general.bitwarden', 'seafile_service', field='username') | first }}"
        seafile_admin_password: "{{ lookup('community.general.bitwarden', 'seafile_service', field='password') | first }}"
        seafile_db_root_password: "{{ lookup('community.general.bitwarden', 'seafile_service', field='rootdb_password') | first }}"
        seafile_jwt_private_key: "{{ lookup('community.general.bitwarden', 'seafile_service', field='jwt') | first }}"
        immich_db: "{{ lookup('community.general.bitwarden', 'immich_service', field='database') | first }}"
        immich_db_user: "{{ lookup('community.general.bitwarden', 'immich_service', field='dbuser') | first }}"
        immich_db_password: "{{ lookup('community.general.bitwarden', 'immich_service', field='dbpassword') | first }}"
        onlyoffice_jwt_secret: "{{ lookup('community.general.bitwarden', 'onlyoffice_service', field='jwt') | first }}"
      tags: server::secrets
  vars:
    directories: "{{ common_directories + server_directories }}"
    directories_to_remove: "{{ common_directories_to_remove + server_directories_to_remove }}"
    packages: "{{ common_packages + server_packages }}"
    packages_to_purge: "{{ server_packages }}"
    python_packages: "{{ common_python_packages + server_python_packages }}"
    repositories: "{{ common_repositories + server_repositories }}"
    systemd_services: "{{ common_systemd_services + server_systemd_services }}"
    docker_networks: "{{ common_docker_networks + server_docker_networks }}"
    docker_services: "{{ common_docker_services + server_docker_services }}"
    docker_services_configs: "{{ common_docker_services_configs + server_docker_services_configs }}"
  tasks:
    - name: Purge
      ansible.builtin.import_tasks: tasks/purge.yml
      when: purge_all
      tags: server::purge

    - name: Deploy
      block:
        - name: Import directories tasks
          ansible.builtin.import_tasks: tasks/system/directories.yml
          tags: server::directories
        
        - name: Import repositories tasks
          ansible.builtin.import_tasks: tasks/system/repositories.yml
          tags: server::repositories
        
        - name: Import packages tasks
          ansible.builtin.import_tasks: tasks/system/packages.yml
          tags: server::packages
        
        - name: Import shell tasks
          ansible.builtin.import_tasks: tasks/system/shell.yml
          tags: server::shell
        
        - name: Import docker tasks
          ansible.builtin.import_tasks: tasks/docker/docker.yml
          tags: server::docker
        
        - name: Import docker services tasks
          ansible.builtin.import_tasks: tasks/docker/services.yml
          tags: server::docker::services
        
        - name: Import systemd services tasks
          ansible.builtin.import_tasks: tasks/system/services.yml
          tags: server::services
