---

- name: Deploy workstation
  hosts: workstations
  become: yes
  handlers:
    - import_tasks: handlers/main.yml
  pre_tasks:
    - name: Get secrets
      ansible.builtin.set_fact:
        mega_username: "{{ lookup('community.general.bitwarden', 'rclone_remotes', field='mega_username') | first }}"
        mega_encpassword: "{{ lookup('community.general.bitwarden', 'rclone_remotes', field='mega_encpassword') | first }}"
      tags: workstation::secrets
  tasks:
    - name: Purge
      ansible.builtin.import_tasks: tasks/purge.yml
      when: purge_all
      tags: workstation::purge

    - name: Deploy
      block:        
        - name: Import repositories tasks
          ansible.builtin.import_tasks: tasks/system/repositories.yml
          vars:
            repositories: "{{ workstation_repositories }}"
          tags: workstation::repositories
        
        - name: Import packages tasks
          ansible.builtin.import_tasks: tasks/system/packages.yml
          vars:
            packages: "{{ common_packages + workstation_packages }}"
            deb_packages: "{{ common_deb_packages + workstation_deb_packages }}"
            python_packages: "{{ workstation_python_packages }}"
          tags: workstation::packages
        
        - name: Import filesystem tasks
          ansible.builtin.import_tasks: tasks/system/filesystem.yml
          vars:
            directories: "{{ common_directories + workstation_directories }}"
            disk_partitions: []
            disk_vgs: []
            disk_lvs: []
          tags: workstation::filesystem

        - name: Import shell tasks
          ansible.builtin.import_tasks: tasks/system/shell.yml
          tags: workstation::shell
        
        - name: Import rclone tasks
          ansible.builtin.import_tasks: tasks/system/rclone.yml
          vars:
            rclone_configs: "{{ common_rclone_configs + workstation_rclone_configs }}"
            rclone_mounts: "{{ common_rclone_mounts + workstation_rclone_mounts }}"
          tags: workstation::rclone
        
        - name: Import docker tasks
          ansible.builtin.import_tasks: tasks/docker/docker.yml
          vars:
            docker_networks: "{{ workstation_docker_networks }}"
          tags: workstation::docker
        
        - name: Import docker services tasks
          ansible.builtin.import_tasks: tasks/docker/services.yml
          vars:
            docker_services: "{{ workstation_docker_services }}"
            docker_services_configs: "{{ workstation_docker_services_configs }}"
            docker_services_crons: "{{ workstation_docker_services_crons }}"
          tags: workstation::docker::services

        - name: Import systemd services tasks
          ansible.builtin.import_tasks: tasks/system/services.yml
          vars:
            systemd_services: "{{ workstation_systemd_services }}"
          tags: workstation::services