---

- name: Deploy workstation
  hosts: workstations
  become: yes
  vars:
    directories: "{{ common_directories + workstation_directories }}"
    directories_to_remove: "{{ common_directories_to_remove + workstation_directories_to_remove }}"
    packages: "{{ common_packages + workstation_packages }}"
    packages_to_purge: "{{ workstation_packages }}"
    repositories: "{{ common_repositories + workstation_repositories }}"
    systemd_services: "{{ common_systemd_services + workstation_systemd_services }}"
    docker_services: "{{ common_docker_services + workstation_docker_services }}"
  tasks:
    - name: Purge
      ansible.builtin.import_tasks: tasks/purge.yml
      when: purge_all
      tags: workstation::purge

    - name: Deploy
      block:
        - name: Import directories tasks
          ansible.builtin.import_tasks: tasks/system/directories.yml
          tags: workstation::directories
        
        - name: Import repositories tasks
          ansible.builtin.import_tasks: tasks/system/repositories.yml
          tags: workstation::repositories
        
        - name: Import packages tasks
          ansible.builtin.import_tasks: tasks/system/packages.yml
          tags: workstation::packages
        
        - name: Import shell tasks
          ansible.builtin.import_tasks: tasks/system/shell.yml
          tags: workstation::shell
        
        - name: Import docker tasks
          ansible.builtin.import_tasks: tasks/docker/docker.yml
          tags: workstation::docker
        
        - name: Import docker services tasks
          ansible.builtin.import_tasks: tasks/docker/services.yml
          tags: workstation::docker::services

        - name: Import systemd services tasks
          ansible.builtin.import_tasks: tasks/system/services.yml
          tags: workstation::services
