apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.8.*"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 1h
  values:
    defaultSettings:
      defaultReplicaCount: 3
      defaultDataPath: /mnt/longhorn
      storageMinimalAvailablePercentage: 15
      storageOverProvisioningPercentage: 150

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Retain