---

k8s_required_kernel_modules:
  - overlay
  - br_netfilter

k8s_repositories:
  - name: "k8s"
    repo_url: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/"
    gpg_url: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key"
    components:
      - "/"

k8s_packages:
  - kubelet
  - kubeadm
  - kubectl

k8s_nodes_packages:
  - apt-transport-https 
  - ca-certificates 
  - curl 
  - gnupg
  - containerd
  - open-iscsi
  - nfs-common
  - cryptsetup
  - conntrack
  - socat
  - ebtables
  - ethtool

k8s_vip: "{{ lan_prefix }}.50"
k8s_interface: eth0
cilium_version: 1.16.4