---

- name: Install & config Promtail
  block:
    - name: Install Promtail
      ansible.builtin.apt:
        deb: "{{ promtail_package }}"

    - name: Template config file
      ansible.builtin.template:
        src: "../templates/promtail/promtail-config.yml.j2"
        dest: "/etc/promtail/config.yml"
    
    - name: Restart promtail service
      ansible.builtin.systemd:
        name: promtail
        state: restarted
        daemon_reload: true

- name: Install & config Node Exporter
  block:
    - name: Unarchive Node Exporter
      ansible.builtin.unarchive:
        src: "{{ node_exporter_archive_url }}"
        dest: /tmp/
        remote_src: true

    - name: Copy node_exporter binary
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-arm64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: "0755"
        remote_src: true
    
    - name: Configure and start node_exporter systemd service
      ansible.builtin.import_tasks: services.yml
      vars:
        systemd_services: "{{ node_exporter_systemd_service }}"